$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$studyPath = Join-Path $root "MacroMicro_Simplified_v0.5.12.ts"
$tosStudyPath = Join-Path $root "_dk_codex_macro_micro_v1.ts"

function Assert-True {
    param(
        [bool] $Condition,
        [string] $Message
    )

    if (-not $Condition) {
        throw $Message
    }
}

function Assert-Contains {
    param(
        [string] $Text,
        [string] $Needle,
        [string] $Description
    )

    Assert-True -Condition $Text.Contains($Needle) -Message "Missing: $Description"
}

function Assert-Before {
    param(
        [string] $Text,
        [string] $Earlier,
        [string] $Later,
        [string] $Description
    )

    $earlierIndex = $Text.IndexOf($Earlier)
    $laterIndex = $Text.IndexOf($Later)

    Assert-True -Condition ($earlierIndex -ge 0) -Message "Missing order source: $Description"
    Assert-True -Condition ($laterIndex -ge 0) -Message "Missing order target: $Description"
    Assert-True -Condition ($earlierIndex -lt $laterIndex) -Message "Invalid ThinkScript definition order: $Description"
}

Assert-True -Condition (Test-Path -LiteralPath $studyPath) -Message "Study file does not exist: $studyPath"
Assert-True -Condition (Test-Path -LiteralPath $tosStudyPath) -Message "TOS import study file does not exist: $tosStudyPath"

$text = Get-Content -LiteralPath $studyPath -Raw
$tosText = Get-Content -LiteralPath $tosStudyPath -Raw

Assert-Contains $text "# Version: v0.5.12" "v0.5.12 version header"
Assert-Contains $text "# TOS Study: _dk_codex_macro_micro_v1" "TOS study name header"
Assert-Contains $text "declare upper;" "upper price-chart declaration"
Assert-Contains $text 'DefineGlobalColor("CautionAmber", CreateColor(180, 95, 0));' "readable caution amber color"
Assert-True -Condition ($tosText -eq $text) -Message "TOS import study file must match MacroMicro_Simplified_v0.5.12.ts exactly"
Assert-Contains $text "Timeframe focus: 5m first, then 15m validation/tuning." "5m-first tuning note"
Assert-Contains $text "input useFifteenMinuteProfile = no;" "5m profile remains default"
Assert-Contains $text "input fifteenMinuteScoreTriggerFreshBars = 1;" "15m score freshness profile"
Assert-Contains $text "input fifteenMinuteResetSameSideAfterBars = 10;" "15m same-side reset profile"
Assert-Contains $text "def activeScoreTriggerFreshBars" "active score freshness selection"
Assert-Contains $text "def activeResetSameSideAfterBars" "active same-side reset selection"
Assert-Contains $text "BarsSinceTrue(longScoreCrossEvent) <= activeScoreTriggerFreshBars" "long trigger freshness uses active profile"
Assert-Contains $text "BarsSinceTrue(shortScoreCrossEvent) <= activeScoreTriggerFreshBars" "short trigger freshness uses active profile"
Assert-Contains $text 'AddLabel(dashOK, "PROFILE: "' "profile dashboard label"
Assert-Contains $text "def standbyThreshold = 4;" "4/6 standby threshold"
Assert-Contains $text "def triggerThreshold = 5;" "5/6 trigger threshold"
Assert-Contains $text "input dangerScoreThreshold = 3;" "danger score threshold"
Assert-Contains $text "input dangerDropFromPeak = 2;" "danger drop from peak"
Assert-Contains $text "plot StandbyLongDot" "long standby dot plot"
Assert-Contains $text "plot StandbyShortDot" "short standby dot plot"
Assert-Contains $text "input useKnownVisibleSignalArrows = yes;" "known-visible signal arrow routing toggle"
Assert-True -Condition (-not $text.Contains("input showArrowMarkerBubbles")) -Message "Marker bubbles still depend on a new saved TOS input"
Assert-Contains $text "input showSignalBubbles = no;" "normal signal bubbles default off for arrows-first v0.5.8 review"
Assert-Contains $text "input showContinuationAnchorArrows = yes;" "continuation anchor arrows default on"
Assert-Contains $text "input showFailsafeSignalBubbles = no;" "failsafe setup bubbles default off after v0.5.6 noise review"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+SignalLongV055Arrow\b").Count -eq 0) -Message "Old v0.5.5 SignalLongV055Arrow plot is still present"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+SignalShortV055Arrow\b").Count -eq 0) -Message "Old v0.5.5 SignalShortV055Arrow plot is still present"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+VisibleLongArrow\b").Count -eq 0) -Message "Old VisibleLongArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+VisibleShortArrow\b").Count -eq 0) -Message "Old VisibleShortArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+LongArrow\b").Count -eq 0) -Message "Old LongArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+ShortArrow\b").Count -eq 0) -Message "Old ShortArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "PaintingStrategy\.ARROW_UP").Count -eq 1) -Message "Expected exactly one up-arrow painting strategy: DebugBigUpArrow as the known-visible real signal path"
Assert-True -Condition ([regex]::Matches($text, "PaintingStrategy\.ARROW_DOWN").Count -eq 1) -Message "Expected exactly one down-arrow painting strategy: DebugBigArrow as the known-visible real signal path"
Assert-Contains $text "def longCandleConfirm" "long candle confirmation"
Assert-Contains $text "input allowCautionFourOfSix = yes;" "4/6 caution entry toggle"
Assert-Contains $text "def microLongOK = microFast > microSlow;" "micro score decoupled from volume pressure"
Assert-Contains $text "def microShortOK = microFast < microSlow;" "micro short score decoupled from volume pressure"
Assert-True -Condition (-not $text.Contains("def microLongOK = microFast > microSlow and buyPressure;")) -Message "Old volume-pressure-gated long micro score is still present"
Assert-True -Condition (-not $text.Contains("def microShortOK = microFast < microSlow and sellPressure;")) -Message "Old volume-pressure-gated short micro score is still present"
Assert-Contains $text "input scoreTriggerFreshBars = 3;" "fresh score trigger window"
Assert-Contains $text "def longScoreFresh" "fresh long score-cross window"
Assert-Contains $text "def shortScoreFresh" "fresh short score-cross window"
Assert-Contains $text "def longEntryConfirm" "relaxed long entry candle confirmation"
Assert-Contains $text "def shortEntryConfirm" "relaxed short entry candle confirmation"
Assert-Contains $text "input fastBreakTRFactor = 1.35;" "fast break range factor"
Assert-Contains $text "input fastBreakLookback = 3;" "fast break lookback"
Assert-Contains $text "input continuationBreakLookback = 2;" "continuation break lookback"
Assert-Contains $text "input continuationRangeFactor = 0.35;" "continuation pressure range factor"
Assert-Contains $text "input setupPulseBars = 5;" "moderate 5/6 setup pulse interval"
Assert-True -Condition (-not $text.Contains("input setupPulseBars = 1;")) -Message "Setup pulse interval is still every bar and will spam the chart"
Assert-Contains $text "def fastBreakVolumeOK" "fast break volume guard"
Assert-Contains $text "def fastBreakoutConfirm" "fast upside breakout confirmation"
Assert-Contains $text "def fastBreakdownConfirm" "fast downside breakdown confirmation"
Assert-Contains $text "input biasFlipMinScore = 2;" "fast bias-flip minimum opposite score"
Assert-Contains $text "input biasFlipRequiresVWAPBreak = yes;" "fast bias-flip VWAP break guard"
Assert-Contains $text "def fastFlipShortSetup" "fast breakdown bias-flip short setup"
Assert-Contains $text "def fastFlipLongSetup" "fast breakout bias-flip long setup"
Assert-Contains $text "def fastFlipShortArrow" "fast breakdown bias-flip short arrow"
Assert-Contains $text "def fastFlipLongArrow" "fast breakout bias-flip long arrow"
Assert-Contains $text "def shortContinuationPressure" "short 4/6 continuation pressure setup"
Assert-Contains $text "def longContinuationPressure" "long 4/6 continuation pressure setup"
Assert-Contains $text "def longSetupPulseReady" "long 5/6 setup pulse readiness"
Assert-Contains $text "def shortSetupPulseReady" "short 5/6 setup pulse readiness"
Assert-Contains $text "def setupPulseState" "recursive setup pulse state"
Assert-Contains $text "def setupPulseLongArrow = longSetupPulseReady and (setupPulseState[1] <= 0 or setupPulseState[1] >= setupPulseBars);" "dense long setup pulse arrow"
Assert-Contains $text "def setupPulseShortArrow = shortSetupPulseReady and (setupPulseState[1] >= 0 or AbsValue(setupPulseState[1]) >= setupPulseBars);" "dense short setup pulse arrow"
Assert-Contains $text "def shortContinuationArrow" "short continuation caution arrow"
Assert-Contains $text "def longContinuationArrow" "long continuation caution arrow"
Assert-Contains $text "def continuationAnchorLongArrow = showContinuationAnchorArrows and longContinuationPressure and longScore >= triggerThreshold;" "persistent long continuation anchor arrow"
Assert-Contains $text "def continuationAnchorShortArrow = showContinuationAnchorArrows and shortContinuationPressure and shortScore >= triggerThreshold;" "persistent short continuation anchor arrow"
Assert-Contains $text "def visualLongSetupReady = longSetupPulseReady;" "visual long setup-ready state"
Assert-Contains $text "def visualShortSetupReady = shortSetupPulseReady;" "visual short setup-ready state"
Assert-Contains $text "def realLongEntry = newLongEntry or practicalLongArrow or fastFlipLongArrow or longContinuationArrow;" "real long entry excludes visual-only setup pulse"
Assert-Contains $text "def realShortEntry = newShortEntry or practicalShortArrow or fastFlipShortArrow or shortContinuationArrow;" "real short entry excludes visual-only setup pulse"
Assert-Contains $text "def visibleLongSignal = realLongEntry or continuationAnchorLongArrow or visualLongSetupReady;" "visible long signal includes setup-ready markers without resetting trade tracking"
Assert-Contains $text "def visibleShortSignal = realShortEntry or continuationAnchorShortArrow or visualShortSetupReady;" "visible short signal includes setup-ready markers without resetting trade tracking"
Assert-Contains $text "def arrowMarkerLong = visibleLongSignal;" "compact long marker follows visible long signal"
Assert-Contains $text "def arrowMarkerShort = visibleShortSignal;" "compact short marker follows visible short signal"
Assert-Contains $text "def longSignalCaution = longScore < triggerThreshold or longTradeCaution or fastFlipLongArrow or longContinuationArrow or setupPulseLongArrow;" "setup pulse long is marked caution"
Assert-Contains $text "def shortSignalCaution = shortScore < triggerThreshold or shortTradeCaution or fastFlipShortArrow or shortContinuationArrow or setupPulseShortArrow;" "setup pulse short is marked caution"
Assert-Contains $text '"FLIP S "' "fast flip short signal bubble"
Assert-Contains $text '"FLIP L "' "fast flip long signal bubble"
Assert-Contains $text '"CONT S "' "continuation short signal bubble"
Assert-Contains $text '"CONT L "' "continuation long signal bubble"
Assert-Contains $text '"SETUP S "' "setup pulse short signal bubble"
Assert-Contains $text '"SETUP L "' "setup pulse long signal bubble"
Assert-Contains $text "plot MarkerLongDotV0511 =" "fresh long marker dot fallback plot"
Assert-Contains $text "plot MarkerShortDotV0511 =" "fresh short marker dot fallback plot"
Assert-Contains $text "if arrowMarkerLong then low - liveArrowOff else Double.NaN;" "long marker dot is driven directly by visible signal"
Assert-Contains $text "if arrowMarkerShort then high + liveArrowOff else Double.NaN;" "short marker dot is driven directly by visible signal"
Assert-Contains $text "MarkerLongDotV0511.SetPaintingStrategy(PaintingStrategy.POINTS);" "long marker dot uses points instead of arrow painting"
Assert-Contains $text "MarkerShortDotV0511.SetPaintingStrategy(PaintingStrategy.POINTS);" "short marker dot uses points instead of arrow painting"
Assert-Contains $text "    arrowMarkerLong," "hardwired compact long marker bubble"
Assert-Contains $text "    arrowMarkerShort," "hardwired compact short marker bubble"
Assert-True -Condition (-not $text.Contains("showArrowMarkerBubbles and arrowMarkerLong")) -Message "Long marker bubble still depends on showArrowMarkerBubbles"
Assert-True -Condition (-not $text.Contains("showArrowMarkerBubbles and arrowMarkerShort")) -Message "Short marker bubble still depends on showArrowMarkerBubbles"
Assert-Contains $text '"L"' "compact long marker label"
Assert-Contains $text '"S"' "compact short marker label"
Assert-Contains $text "Color.MAGENTA" "compact long marker color"
Assert-Contains $text "Color.CYAN" "compact short marker color"
Assert-Contains $text '"MARKER: "' "dashboard marker state label"
Assert-Contains $text 'AddLabel(yes, "BUILD: v0.5.12 DIAG", Color.BLACK);' "always-visible build version dashboard label"
Assert-Contains $text 'AddLabel(yes, "MARKER: " + (if arrowMarkerLong then "L" else if arrowMarkerShort then "S" else "NONE"), if arrowMarkerLong then Color.MAGENTA else if arrowMarkerShort then Color.CYAN else Color.GRAY);' "always-visible marker state dashboard label"
Assert-True -Condition (-not $text.Contains('AddLabel(dashOK, "MARKER: "')) -Message "Marker state label still depends on showDashboard"
Assert-Contains $text "plot BuildProofDotV0512 =" "hardwired last-bar proof dot"
Assert-Contains $text "if lastVisibleBar then high + liveArrowOff else Double.NaN;" "proof dot is independent of signal"
Assert-Contains $text "BuildProofDotV0512.SetPaintingStrategy(PaintingStrategy.POINTS);" "proof dot uses point rendering"
Assert-Contains $text '"v0.5.12 TEST"' "last-bar build bubble proves chart-bubble path"
Assert-Contains $text '"FLIP SHORT"' "fast flip short dashboard trigger"
Assert-Contains $text '"FLIP LONG"' "fast flip long dashboard trigger"
Assert-Contains $text '"CONT SHORT"' "continuation short dashboard trigger"
Assert-Contains $text '"CONT LONG"' "continuation long dashboard trigger"
Assert-Contains $text '"SETUP SHORT"' "setup pulse short dashboard trigger"
Assert-Contains $text '"SETUP LONG"' "setup pulse long dashboard trigger"
Assert-Contains $text '"BREAKDOWN"' "fast breakdown next-state diagnostic"
Assert-Contains $text '"BREAKOUT"' "fast breakout next-state diagnostic"
Assert-Contains $text '"CONTINUE S"' "short continuation next-state diagnostic"
Assert-Contains $text '"CONTINUE L"' "long continuation next-state diagnostic"
Assert-Contains $text '"PULSE READY"' "setup pulse fired next-state diagnostic"
Assert-Contains $text '"SETUP READY"' "setup-ready next-state diagnostic"
Assert-Contains $text "def longEntryConfirm = longCandleConfirm or longBreakConfirm or fastBreakoutConfirm;" "fast breakout participates in long entry confirmation"
Assert-Contains $text "def shortEntryConfirm = shortCandleConfirm or shortBreakConfirm or fastBreakdownConfirm;" "fast breakdown participates in short entry confirmation"
Assert-Contains $text "fastBreakdownConfirm" "fast breakdown missed-dump guard"
Assert-Contains $text "def longScoreCrossTrigger" "long score-cross entry trigger"
Assert-Contains $text "def sustainedLongTrigger" "sustained 5/6 long trigger"
Assert-Contains $text "def sustainedShortTrigger" "sustained 5/6 short trigger"
Assert-Contains $text "def cooldownJustCleared" "cooldown clear pulse"
Assert-Contains $text "def longEntryPulse" "anti-starvation long entry pulse"
Assert-Contains $text "def longReadyEntry" "ready long entry fallback"
Assert-Contains $text "def shortReadyEntry" "ready short entry fallback"
Assert-Contains $text "def shortEntryPulse" "anti-starvation short entry pulse"
Assert-Contains $text "def barsSincePlottedEntry" "cooldown driven by plotted entries"
Assert-Contains $text "def entryState" "compile-safe recursive entry state"
Assert-Contains $text "def longEntryCandidate = rawLongEntry or longReadyEntry;" "long entry candidate before entry state"
Assert-Contains $text "def shortEntryCandidate = rawShortEntry or shortReadyEntry;" "short entry candidate before entry state"
Assert-Contains $text "def sameSideLongExpired" "same-side long time reset"
Assert-Contains $text "def sameSideShortExpired" "same-side short time reset"
Assert-Before $text "def entryState" "def newLongEntry" "entryState must be defined before derived long arrow"
Assert-Before $text "def entryState" "def newShortEntry" "entryState must be defined before derived short arrow"
Assert-True -Condition (-not $text.Contains("newLongEntry[1]")) -Message "newLongEntry previous-bar reference reintroduced; use entryState instead"
Assert-True -Condition (-not $text.Contains("newShortEntry[1]")) -Message "newShortEntry previous-bar reference reintroduced; use entryState instead"
Assert-Before $text "def lastEntryDir" "lastEntryDir[1]" "lastEntryDir must be defined before previous-bar use"
Assert-Contains $text "entryState[1] > activeResetSameSideAfterBars" "long same-side reset uses active profile"
Assert-Contains $text "entryState[1] < -activeResetSameSideAfterBars" "short same-side reset uses active profile"
Assert-Contains $text "def practicalLongSetup" "practical long setup arrow layer"
Assert-Contains $text "def practicalShortSetup" "practical short setup arrow layer"
Assert-Contains $text "def practicalLongArrow" "practical long arrow edge"
Assert-Contains $text "def practicalShortArrow" "practical short arrow edge"
Assert-Contains $text "def realLongEntry = newLongEntry or practicalLongArrow or fastFlipLongArrow or longContinuationArrow;" "real long entry includes practical setup edge, fast flip edge, and continuation edge"
Assert-Contains $text "def realShortEntry = newShortEntry or practicalShortArrow or fastFlipShortArrow or shortContinuationArrow;" "real short entry includes practical setup edge, fast flip edge, and continuation edge"
Assert-True -Condition (-not $text.Contains("def realLongEntry = newLongEntry or practicalLongArrow or fastFlipLongArrow or longContinuationArrow or setupPulseLongArrow;")) -Message "Visual-only long setup pulse still resets trade tracking"
Assert-True -Condition (-not $text.Contains("def realShortEntry = newShortEntry or practicalShortArrow or fastFlipShortArrow or shortContinuationArrow or setupPulseShortArrow;")) -Message "Visual-only short setup pulse still resets trade tracking"
Assert-Contains $text "longEntryEdge or longReadyEdge or cooldownJustCleared or longTradeJustUnblocked or sameSideLongExpired" "same-side long waits for next valid candidate after reset"
Assert-Contains $text "shortEntryEdge or shortReadyEdge or cooldownJustCleared or shortTradeJustUnblocked or sameSideShortExpired" "same-side short waits for next valid candidate after reset"
Assert-True -Condition (-not $text.Contains("def anyEntryEdge = longEntryEdge or shortEntryEdge or longReadyEdge or shortReadyEdge;")) -Message "Candidate ready edges still reset cooldown and can starve historical arrows"
Assert-True -Condition (-not $text.Contains("if anyEntryEdge then 0 else barsSinceEntryEdge[1] + 1")) -Message "Cooldown is still driven by candidate entry edges instead of plotted entries"
Assert-Contains $text "def longCautionSetup" "4/6 long caution setup"
Assert-Contains $text "def shortCautionSetup" "4/6 short caution setup"
Assert-Contains $text "def longSignalCaution" "long signal caution label state"
Assert-Contains $text "def shortSignalCaution" "short signal caution label state"
Assert-Contains $text "input showDebugLabel = yes;" "debug label input"
Assert-Contains $text "input debugForceArrows = no;" "temporary forced arrow debug input defaults off"
Assert-Contains $text "input debugPaintBigArrow = no;" "big arrow debug input defaults off"
Assert-Contains $text "def lastVisibleBar = BarNumber() == HighestAll" "last visible bar detector"
Assert-Contains $text "plot DebugBigArrow" "known-visible big debug arrow plot"
Assert-Contains $text "plot DebugBigArrow =" "known-visible short arrow plot declaration"
Assert-Contains $text "if useKnownVisibleSignalArrows and visibleShortSignal then high + liveArrowOff" "visible short signals use closer live arrow offset"
Assert-Contains $text "else if (debugPaintBigArrow and lastVisibleBar) or (debugForceArrows and debugForcedShortArrow) then high + bigArrowOff" "debug short arrows keep big diagnostic offset"
Assert-Contains $text "DebugBigArrow.SetPaintingStrategy(PaintingStrategy.ARROW_DOWN);" "big debug arrow painting strategy"
Assert-Contains $text "DebugBigArrow.SetLineWeight(5);" "big debug arrow line weight"
Assert-Contains $text "DebugBigArrow.SetDefaultColor(Color.CYAN);" "big debug arrow color"
Assert-Contains $text "plot DebugBigUpArrow =" "known-visible long arrow plot declaration"
Assert-Contains $text "if useKnownVisibleSignalArrows and visibleLongSignal then low - liveArrowOff" "visible long signals use closer live arrow offset"
Assert-Contains $text "else if debugForceArrows and debugForcedLongArrow then low - bigArrowOff" "debug long arrows keep big diagnostic offset"
Assert-Contains $text "DebugBigUpArrow.SetPaintingStrategy(PaintingStrategy.ARROW_UP);" "big up debug arrow painting strategy"
Assert-Contains $text "DebugBigUpArrow.SetLineWeight(5);" "big up debug arrow line weight"
Assert-Contains $text "DebugBigUpArrow.SetDefaultColor(Color.MAGENTA);" "big up debug arrow color"
Assert-Contains $text '"BIG TEST ARROW"' "big debug arrow bubble"
Assert-Contains $text '"BIG TEST"' "big debug trigger dashboard state"
Assert-Contains $text "def debugForcedLongArrow = debugForceArrows and longScore >= triggerThreshold and longScore > shortScore;" "forced long arrow condition ignores trade/RVOL"
Assert-Contains $text "def debugForcedShortArrow = debugForceArrows and shortScore >= triggerThreshold and shortScore > longScore;" "forced short arrow condition ignores trade/RVOL"
Assert-True -Condition (-not $text.Contains("def debugForcedLongArrow = debugForceArrows and longScore >= triggerThreshold and longScore > shortScore and longTradeOK;")) -Message "Debug forced long arrow is still blocked by trade/RVOL"
Assert-True -Condition (-not $text.Contains("def debugForcedShortArrow = debugForceArrows and shortScore >= triggerThreshold and shortScore > longScore and shortTradeOK;")) -Message "Debug forced short arrow is still blocked by trade/RVOL"
Assert-Contains $text "def arrowOff = Max(off, atr * 0.12);" "ATR-aware arrow visibility offset"
Assert-Contains $text "def signalArrowOff = Max(off * 8, atr * 0.30);" "larger visible real-entry arrow offset"
Assert-Contains $text "def liveArrowOff = Max(off * 18, atr * 0.50);" "closer known-visible live arrow offset"
Assert-True -Condition (-not $text.Contains("if useKnownVisibleSignalArrows and realShortEntry then high + liveArrowOff")) -Message "Known-visible short plot still ignores continuation anchors"
Assert-True -Condition (-not $text.Contains("if useKnownVisibleSignalArrows and realLongEntry then low - liveArrowOff")) -Message "Known-visible long plot still ignores continuation anchors"
Assert-True -Condition (-not $text.Contains("plot SignalLongV055Arrow = if realLongEntry")) -Message "Real long entries still use the v0.5.5 hidden-prone plot"
Assert-True -Condition (-not $text.Contains("plot SignalShortV055Arrow = if realShortEntry")) -Message "Real short entries still use the v0.5.5 hidden-prone plot"
Assert-True -Condition (-not $text.Contains("plot VisibleLongArrow = if newLongEntry or debugForcedLongArrow")) -Message "Real long arrow still includes forced debug arrows"
Assert-True -Condition (-not $text.Contains("plot VisibleShortArrow = if newShortEntry or debugForcedShortArrow")) -Message "Real short arrow still includes forced debug arrows"
Assert-Contains $text "showFailsafeSignalBubbles and setupPulseLongArrow" "ungated failsafe long setup bubble"
Assert-Contains $text "showFailsafeSignalBubbles and setupPulseShortArrow" "ungated failsafe short setup bubble"
Assert-Contains $text '"FORCED: "' "forced arrow condition dashboard label"
Assert-Contains $text "Color.MAGENTA" "forced long debug arrow color"
Assert-Contains $text "Color.CYAN" "forced short debug arrow color"
Assert-Contains $text '"TEST L "' "forced long debug bubble"
Assert-Contains $text '"TEST S "' "forced short debug bubble"
Assert-Contains $text "debugForceArrows and debugForcedLongArrow and !realLongEntry," "forced long debug bubble ignores signal-bubble toggle"
Assert-Contains $text "debugForceArrows and debugForcedShortArrow and !realShortEntry," "forced short debug bubble ignores signal-bubble toggle"
Assert-True -Condition (-not $text.Contains("showSignalBubbles and debugForcedLongArrow")) -Message "Forced long debug bubble is still hidden by showSignalBubbles"
Assert-True -Condition (-not $text.Contains("showSignalBubbles and debugForcedShortArrow")) -Message "Forced short debug bubble is still hidden by showSignalBubbles"
Assert-Contains $text '"TEST LONG"' "forced long trigger dashboard state"
Assert-Contains $text '"TEST SHORT"' "forced short trigger dashboard state"
Assert-Contains $text '"DEBUG FORCE ARROWS"' "visible forced-arrow debug dashboard label"
Assert-Contains $text '"BLOCKED BY: "' "hard-block diagnostic dashboard label"
Assert-Contains $text '"CAUTION BY: "' "caution diagnostic dashboard label"
Assert-Contains $text '"NEXT: "' "next-trigger diagnostic dashboard label"
Assert-True -Condition (-not $text.Contains('"WHY: "')) -Message "Old combined WHY diagnostic label can confuse caution with hard block"
Assert-Contains $text '"SCORE"' "score-first diagnostic state"
Assert-Contains $text '"TIE"' "tie diagnostic state"
Assert-Contains $text '"SETUP: " +' "setup dashboard label"
Assert-True -Condition (-not $text.Contains('"SETUP: " + AsText(dashScore)')) -Message "SETUP label still uses decimal AsText(dashScore)"
Assert-Contains $text "longScore < triggerThreshold" "same-side long reset below trigger"
Assert-Contains $text "shortScore < triggerThreshold" "same-side short reset below trigger"
Assert-Contains $text "def shortCandleConfirm" "short candle confirmation"
Assert-Contains $text "def shortScoreCrossTrigger" "short score-cross entry trigger"
Assert-Contains $text "input minRelVolume = 0.80;" "5m caution RVOL threshold"
Assert-Contains $text "input blockRelVolume = 0.00;" "RVOL no longer hard-blocks qualified setups by default"
Assert-Contains $text "input lowVolumeMomentumATRFactor = 1.20;" "low-volume impulse override range factor"
Assert-True -Condition (-not $text.Contains("input blockRelVolume = 0.10;")) -Message "Old 0.10 RVOL hard block is still present"
Assert-True -Condition (-not $text.Contains("input blockRelVolume = 0.35;")) -Message "Old 0.35 RVOL hard block is still present"
Assert-True -Condition (-not $text.Contains("input blockRelVolume = 0.60;")) -Message "Old 0.60 RVOL hard block is still present"
Assert-Contains $text "def extremeLowRelVolume" "extreme low relative volume gate"
Assert-Contains $text "def exceptionalLongMomentum" "exceptional long momentum override"
Assert-Contains $text "def exceptionalShortMomentum" "exceptional short momentum override"
Assert-Contains $text "def lowVolumeLongMomentum" "low-volume long momentum override"
Assert-Contains $text "def lowVolumeShortMomentum" "low-volume short momentum override"
Assert-Contains $text "def longVolumeOK" "long direction volume gate"
Assert-Contains $text "def shortVolumeOK" "short direction volume gate"
Assert-Contains $text "def longVolumeOK = yes;" "long RVOL is not a hard entry blocker"
Assert-Contains $text "def shortVolumeOK = yes;" "short RVOL is not a hard entry blocker"
Assert-Contains $text "def tradeBlocked = structureBlocked;" "trade blocked state does not hard-block solely on RVOL"
Assert-True -Condition (-not $text.Contains("def longVolumeOK = !extremeLowRelVolume")) -Message "Long volume gate still hard-blocks extreme RVOL"
Assert-True -Condition (-not $text.Contains("def shortVolumeOK = !extremeLowRelVolume")) -Message "Short volume gate still hard-blocks extreme RVOL"
Assert-Contains $text "def fastBreakVolumeOK = relVol >= minRelVolume or candleTR >= avgTR20 * lowVolumeMomentumATRFactor;" "fast break can confirm on low-volume impulse"
Assert-Contains $text "def tradeBlocked" "trade blocked state"
Assert-Contains $text "def longTradeOK" "long trade permission state"
Assert-Contains $text "def shortTradeOK" "short trade permission state"
Assert-Contains $text "def trendResetLong" "long trend reset state"
Assert-Contains $text "def trendResetShort" "short trend reset state"
Assert-Contains $text "def continuationLongSignal" "long continuation signal"
Assert-Contains $text "def continuationShortSignal" "short continuation signal"
Assert-Contains $text "def activeTradeScore" "active trade score"
Assert-Contains $text "def peakTradeScore" "peak trade score"
Assert-Contains $text "def longDanger" "long danger state"
Assert-Contains $text "def shortDanger" "short danger state"
Assert-Contains $text "def longDangerEdge" "long danger edge"
Assert-Contains $text "def shortDangerEdge" "short danger edge"
Assert-Contains $text "def longProfitMove = close - activeEntryPrice;" "directional long profit calculation"
Assert-Contains $text "def shortProfitMove = activeEntryPrice - close;" "directional short profit calculation"
Assert-Contains $text "if realLongEntry or realShortEntry then close else activeEntryPrice[1]" "active entry price uses practical real entries"
Assert-Contains $text "if realLongEntry or realShortEntry then atr else lockedATR[1]" "locked ATR uses practical real entries"
Assert-Contains $text "if realLongEntry then 1" "active long direction uses practical real entry"
Assert-Contains $text "else if realShortEntry then -1" "active short direction uses practical real entry"
Assert-Contains $text "def longTargetPrice = activeEntryPrice + lockedATR * targetATRFactor;" "long ATR target"
Assert-Contains $text "def shortTargetPrice = activeEntryPrice - lockedATR * targetATRFactor;" "short ATR target"
Assert-Contains $text "def longStopPrice = activeEntryPrice - lockedATR * stopATRFactor;" "long ATR stop"
Assert-Contains $text "def shortStopPrice = activeEntryPrice + lockedATR * stopATRFactor;" "short ATR stop"
Assert-Contains $text "if showTargetStopLines and activeDir == 1 then longTargetPrice" "long target only while trade is active"
Assert-Contains $text "if showTargetStopLines and activeDir == -1 then shortTargetPrice" "short target only while trade is active"
Assert-Contains $text "if showTargetStopLines and targetHit and activeDir[1] == 1 then longTargetPrice[1]" "long target visible on hit bar"
Assert-Contains $text "if showTargetStopLines and stopHit and activeDir[1] == 1 then longStopPrice[1]" "long stop visible on hit bar"
Assert-Contains $text "showSignalBubbles and realLongEntry" "compact long signal bubble"
Assert-Contains $text "showSignalBubbles and realShortEntry" "compact short signal bubble"
Assert-Contains $text "AddChartBubble(showContinuationBubbles and continuationLongSignal" "long continuation bubble"
Assert-Contains $text "AddChartBubble(showContinuationBubbles and continuationShortSignal" "short continuation bubble"
Assert-Contains $text "AddChartBubble(showDangerBubbles and longDangerEdge" "long danger bubble"
Assert-Contains $text "AddChartBubble(showDangerBubbles and shortDangerEdge" "short danger bubble"
Assert-Contains $text '"ENTRY L "' "entry long bubble label"
Assert-Contains $text '"ADD L "' "add long bubble label"
Assert-Contains $text '"DANGER L "' "danger long bubble label"
Assert-Contains $text '"PT"' "profit target bubble label"
Assert-Contains $text '"SL"' "stop loss bubble label"
Assert-Contains $text '"TRADE: "' "trade dashboard label"
Assert-Contains $text '"OK"' "trade ok dashboard state"
Assert-Contains $text '"CAUTION"' "risk caution dashboard state"
Assert-Contains $text '"BLOCKED"' "trade blocked dashboard state"
Assert-True -Condition (-not $text.Contains("Color.YELLOW")) -Message "Bright Color.YELLOW is still present and hard to read with white TOS text"
Assert-Contains $text 'GlobalColor("CautionAmber")' "amber caution dashboard/bubble colors"

Assert-True -Condition (-not $text.Contains("AbsValue(close - entryPrice)")) -Message "Old absolute target math is still present"
Assert-True -Condition (-not $text.Contains('"RISK: "')) -Message "Old RISK dashboard label is still present"
Assert-True -Condition (-not $text.Contains('"NORMAL"')) -Message "Old risk NORMAL dashboard state is still present"
Assert-True -Condition (-not $text.Contains("plot NeutralUpArrow")) -Message "Old neutral up arrow plot is still present"
Assert-True -Condition (-not $text.Contains("plot NeutralDownArrow")) -Message "Old neutral down arrow plot is still present"
Assert-True -Condition (-not $text.Contains("plot ConfluenceUpArrow")) -Message "Old confluence up arrow plot is still present"
Assert-True -Condition (-not $text.Contains("plot ConfluenceDownArrow")) -Message "Old confluence down arrow plot is still present"

Write-Host "Simplified indicator verification passed."
