$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$studyPath = Join-Path $root "MacroMicro_Simplified_v0.5.42.ts"
$tosStudyPath = Join-Path $root "_dk_codex_macro_micro_v1.ts"
$readableStudyPath = Join-Path $root "MacroMicro_Simplified_v0.5.42_READABLE.txt"
$reviewFixturePath = Join-Path $PSScriptRoot "verify_review_signal_fixture.ps1"
$nanSafeReviewFixturePath = Join-Path $PSScriptRoot "verify_nan_safe_review_fixture.ps1"
$gitAttributesPath = Join-Path $root ".gitattributes"

function Assert-True {
    param(
        [bool] $Condition,
        [string] $Message
    )

    if (-not $Condition) {
        throw $Message
    }
}

function Assert-Contains {
    param(
        [string] $Text,
        [string] $Needle,
        [string] $Description
    )

    Assert-True -Condition $Text.Contains($Needle) -Message "Missing: $Description"
}

function Assert-Before {
    param(
        [string] $Text,
        [string] $Earlier,
        [string] $Later,
        [string] $Description
    )

    $earlierIndex = $Text.IndexOf($Earlier)
    $laterIndex = $Text.IndexOf($Later)

    Assert-True -Condition ($earlierIndex -ge 0) -Message "Missing order source: $Description"
    Assert-True -Condition ($laterIndex -ge 0) -Message "Missing order target: $Description"
    Assert-True -Condition ($earlierIndex -lt $laterIndex) -Message "Invalid ThinkScript definition order: $Description"
}

function Assert-RegexCount {
    param(
        [string] $Text,
        [string] $Pattern,
        [int] $Expected,
        [string] $Description
    )

    $count = [regex]::Matches($Text, $Pattern).Count
    Assert-True -Condition ($count -eq $Expected) -Message "$Description expected $Expected, found $count"
}

function Assert-NoRegex {
    param(
        [string] $Text,
        [string] $Pattern,
        [string] $Description
    )

    Assert-True -Condition (-not [regex]::IsMatch($Text, $Pattern)) -Message $Description
}

function Assert-RenderCallsClosed {
    param(
        [string] $Text,
        [string] $CallName
    )

    $escapedCall = [regex]::Escape($CallName)
    $openCount = [regex]::Matches($Text, "\b$escapedCall\s*\(").Count
    $closedCount = [regex]::Matches($Text, "\b$escapedCall\s*\((?s:.*?)\);").Count
    Assert-True -Condition ($openCount -eq $closedCount) -Message "$CallName render statements are not balanced: $closedCount closed / $openCount opened"
}

Assert-True -Condition (Test-Path -LiteralPath $studyPath) -Message "Study file does not exist: $studyPath"
Assert-True -Condition (Test-Path -LiteralPath $tosStudyPath) -Message "TOS import study file does not exist: $tosStudyPath"
Assert-True -Condition (Test-Path -LiteralPath $readableStudyPath) -Message "Side-panel readable study copy does not exist: $readableStudyPath"
Assert-True -Condition (Test-Path -LiteralPath $reviewFixturePath) -Message "Review signal fixture verifier does not exist: $reviewFixturePath"
Assert-True -Condition (Test-Path -LiteralPath $nanSafeReviewFixturePath) -Message "NaN-safe review fixture verifier does not exist: $nanSafeReviewFixturePath"
Assert-True -Condition (Test-Path -LiteralPath $gitAttributesPath) -Message ".gitattributes must exist to keep TOS/powershell line endings stable"

& $reviewFixturePath | Out-Null
& $nanSafeReviewFixturePath | Out-Null

$text = Get-Content -LiteralPath $studyPath -Raw
$tosText = Get-Content -LiteralPath $tosStudyPath -Raw
$readableText = Get-Content -LiteralPath $readableStudyPath -Raw
$gitAttributesText = Get-Content -LiteralPath $gitAttributesPath -Raw

Assert-RegexCount $text "(?m)^# Version:" 1 "single version header"
Assert-RegexCount $text "(?m)^declare upper;" 1 "single upper declaration"
Assert-NoRegex $text "(?m)^else\b" "Naked top-level else statement detected"
Assert-RenderCallsClosed $text "AddLabel"
Assert-RenderCallsClosed $text "AddChartBubble"
Assert-RenderCallsClosed $text "Alert"
Assert-Contains $gitAttributesText "*.ts text eol=lf" "ThinkScript LF normalization"
Assert-Contains $gitAttributesText "*.ps1 text eol=lf" "PowerShell LF normalization"
Assert-Contains $text "# Version: v0.5.42" "v0.5.42 version header"
Assert-Contains $text "# TOS Study: _dk_codex_macro_micro_v1" "TOS study name header"
Assert-Contains $text "declare upper;" "upper price-chart declaration"
Assert-Contains $text 'DefineGlobalColor("CautionAmber", CreateColor(180, 95, 0));' "readable caution amber color"
Assert-True -Condition ($tosText -eq $text) -Message "TOS import study file must match MacroMicro_Simplified_v0.5.42.ts exactly"
Assert-True -Condition ($readableText -eq $text) -Message "Side-panel readable .txt copy must match MacroMicro_Simplified_v0.5.42.ts exactly"
Assert-Contains $text "Timeframe focus: 5m first, then 15m validation/tuning." "5m-first tuning note"
Assert-Contains $text "input useFifteenMinuteProfile = no;" "5m profile remains default"
Assert-Contains $text "input fifteenMinuteScoreTriggerFreshBars = 1;" "15m score freshness profile"
Assert-Contains $text "input fifteenMinuteResetSameSideAfterBars = 10;" "15m same-side reset profile"
Assert-Contains $text "def activeScoreTriggerFreshBars" "active score freshness selection"
Assert-Contains $text "def activeResetSameSideAfterBars" "active same-side reset selection"
Assert-Contains $text "BarsSinceTrue(longScoreCrossEvent) <= activeScoreTriggerFreshBars" "long trigger freshness uses active profile"
Assert-Contains $text "BarsSinceTrue(shortScoreCrossEvent) <= activeScoreTriggerFreshBars" "short trigger freshness uses active profile"
Assert-Contains $text 'AddLabel(dashOK, "PROFILE: "' "profile dashboard label"
Assert-Contains $text "def standbyThreshold = 4;" "4/6 standby threshold"
Assert-Contains $text "def triggerThreshold = 5;" "5/6 trigger threshold"
Assert-Contains $text "input dangerScoreThreshold = 3;" "danger score threshold"
Assert-Contains $text "input dangerDropFromPeak = 2;" "danger drop from peak"
Assert-Contains $text "plot StandbyLongDot" "long standby dot plot"
Assert-Contains $text "plot StandbyShortDot" "short standby dot plot"
Assert-True -Condition (-not $text.Contains("input useKnownVisibleSignalArrows")) -Message "Legacy known-visible arrow toggle should be removed after fresh review arrows take over"
Assert-True -Condition (-not $text.Contains("input showArrowMarkerBubbles")) -Message "Marker bubbles still depend on a new saved TOS input"
Assert-Contains $text "input showSignalBubbles = no;" "normal signal bubbles default off for arrows-first v0.5.8 review"
Assert-Contains $text "input showContinuationAnchorArrows = no;" "persistent continuation anchor arrows default off for quieter review"
Assert-Contains $text "input showFailsafeSignalBubbles = no;" "failsafe setup bubbles default off after v0.5.6 noise review"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+SignalLongV055Arrow\b").Count -eq 0) -Message "Old v0.5.5 SignalLongV055Arrow plot is still present"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+SignalShortV055Arrow\b").Count -eq 0) -Message "Old v0.5.5 SignalShortV055Arrow plot is still present"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+VisibleLongArrow\b").Count -eq 0) -Message "Old VisibleLongArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+VisibleShortArrow\b").Count -eq 0) -Message "Old VisibleShortArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+LongArrow\b").Count -eq 0) -Message "Old LongArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+ShortArrow\b").Count -eq 0) -Message "Old ShortArrow plot name is still present and may inherit hidden TOS settings"
Assert-True -Condition ([regex]::Matches($text, "PaintingStrategy\.ARROW_UP").Count -eq 3) -Message "Expected three up-arrow painting strategies: DebugBigUpArrow, review long, and score-probe long"
Assert-True -Condition ([regex]::Matches($text, "PaintingStrategy\.ARROW_DOWN").Count -eq 3) -Message "Expected three down-arrow painting strategies: DebugBigArrow, review short, and score-probe short"
Assert-True -Condition (-not $text.Contains("PaintingStrategy.BOOLEAN_ARROW")) -Message "Do not use BOOLEAN_ARROW; use value-based ARROW_UP/ARROW_DOWN plots at a price offset"
Assert-NoRegex $text "(?m)^\s*rec\s+\w+\s*=\s*(Max|Min)\s*\(\s*if\b" "Risky recursive Max/Min self-reference pattern detected"
Assert-Contains $text "def longCandleConfirm" "long candle confirmation"
Assert-Contains $text "input allowCautionFourOfSix = yes;" "4/6 caution entry toggle"
Assert-Contains $text "def microLongOK = microFast > microSlow;" "micro score decoupled from volume pressure"
Assert-Contains $text "def microShortOK = microFast < microSlow;" "micro short score decoupled from volume pressure"
Assert-True -Condition (-not $text.Contains("def microLongOK = microFast > microSlow and buyPressure;")) -Message "Old volume-pressure-gated long micro score is still present"
Assert-True -Condition (-not $text.Contains("def microShortOK = microFast < microSlow and sellPressure;")) -Message "Old volume-pressure-gated short micro score is still present"
Assert-Contains $text "input scoreTriggerFreshBars = 3;" "fresh score trigger window"
Assert-Contains $text "def longScoreFresh" "fresh long score-cross window"
Assert-Contains $text "def shortScoreFresh" "fresh short score-cross window"
Assert-Contains $text "def longEntryConfirm" "relaxed long entry candle confirmation"
Assert-Contains $text "def shortEntryConfirm" "relaxed short entry candle confirmation"
Assert-Contains $text "input fastBreakTRFactor = 1.35;" "fast break range factor"
Assert-Contains $text "input fastBreakLookback = 3;" "fast break lookback"
Assert-Contains $text "input continuationBreakLookback = 2;" "continuation break lookback"
Assert-Contains $text "input continuationRangeFactor = 0.35;" "continuation pressure range factor"
Assert-Contains $text "input setupPulseBars = 5;" "normal setup pulse interval remains moderate"
Assert-Contains $text "input rawSetupBubbleBars = 13;" "direct raw proof bubbles use a slower visual cadence"
Assert-Contains $text "input showReviewSignalArrows = yes;" "working-style trade-review arrows default on"
Assert-Contains $text "input showSetupReviewArrows = yes;" "balanced setup-review arrows default on"
Assert-Contains $text "input setupReviewRefreshBars = 21;" "sustained setup review refresh cadence is quieter after v0.5.27 noise review"
Assert-Contains $text "input reviewVisualMinBars = 10;" "visual review arrows throttle repeated same-side clusters"
Assert-Contains $text "input reviewChopFilterEnabled = yes;" "review arrows default to chop-filtered after v0.5.29 chop screenshots"
Assert-Contains $text "input reviewChopLookbackBars = 12;" "review chop filter uses local trend-efficiency lookback"
Assert-Contains $text "input minReviewTrendEfficiency = 0.30;" "review chop filter requires directional efficiency"
Assert-Contains $text "input minReviewScoreSeparation = 2;" "review chop filter requires score dominance"
Assert-Contains $text "input reviewConflictFilterEnabled = yes;" "review mixed-direction conflict filter defaults on"
Assert-Contains $text "input reviewConflictLookbackBars = 21;" "review mixed-direction conflict lookback default widened after v0.5.33 showed low DBG BOTH counts"
Assert-Contains $text "input minConflictEscapeTrendEfficiency = 0.45;" "mixed-conflict escape requires stricter trend efficiency than the general chop gate"
Assert-Contains $text "input minConflictEscapeScoreSeparation = 3;" "mixed-conflict escape requires stronger score dominance than the general chop gate"
Assert-Contains $text "input reviewPressureConflictLookbackBars = 34;" "raw-pressure flip guard watches a longer opposite-pressure window"
Assert-Contains $text "input minPressureConflictEscapeTrendEfficiency = 0.60;" "raw-pressure flip escape needs stronger directional efficiency"
Assert-Contains $text "input minPressureConflictEscapeScoreSeparation = 5;" "raw-pressure flip escape needs stronger score dominance"
Assert-Contains $text "input reviewArrowRiskBufferATR = 0.40;" "review arrows sit beyond review stop bubbles"
Assert-Contains $text "input reviewTargetATRFactor = 2.0;" "review target is wider than the real trade target for screenshot evaluation"
Assert-Contains $text "input reviewStopATRFactor = 1.0;" "review stop remains one ATR for visual risk comparison"
Assert-Contains $text "input showReviewTargetStopLines = yes;" "review-only target/stop lines default on for screenshot validation"
Assert-Contains $text "input showReviewTargetStopBubbles = yes;" "review-only target/stop bubbles default on for screenshot validation"
Assert-Contains $text "input reviewTargetStopHoldBars = 24;" "review-only target/stop plans persist long enough to inspect on 5m screenshots"
Assert-Contains $text "input reviewContinuationBreakLookbackBars = 5;" "review continuation arrows need a wider structure break than raw continuation pressure"
Assert-Contains $text "input minReviewContinuationScoreSeparation = 2;" "review continuation arrows need side dominance before bypassing chop"
Assert-Contains $text "input reviewFastBreakLookbackBars = 5;" "review fast-break arrows need a wider structure break than raw fast breaks"
Assert-Contains $text "input reviewFastBreakTRFactor = 1.60;" "review fast-break arrows need stronger range expansion than raw fast breaks"
Assert-Contains $text "input reviewTrendBreakLookbackBars = 8;" "normal efficient-score review arrows need a wider structure break in chop"
Assert-Contains $text "input reviewTrendCloseConfirmRatio = 0.45;" "normal efficient-score review arrows need directional candle close confirmation"
Assert-Contains $text "input reviewDebugLookbackBars = 200;" "review debug count lookback"
Assert-Contains $text "input showScoreProbeArrows = no;" "score-probe diagnostic arrows default off after v0.5.26 visual cleanup"
Assert-True -Condition (-not $text.Contains("input showRawSetupArrows")) -Message "Raw setup arrow input should not remain as a default visual path"
Assert-Contains $text "input showRawProofBubbles = no;" "direct raw proof bubbles default off after arrow rendering was proven"
Assert-Contains $text "def fastBreakVolumeOK" "fast break volume guard"
Assert-Contains $text "def fastBreakoutConfirm" "fast upside breakout confirmation"
Assert-Contains $text "def fastBreakdownConfirm" "fast downside breakdown confirmation"
Assert-Contains $text "input biasFlipMinScore = 2;" "fast bias-flip minimum opposite score"
Assert-Contains $text "input biasFlipRequiresVWAPBreak = yes;" "fast bias-flip VWAP break guard"
Assert-Contains $text "def fastFlipShortSetup" "fast breakdown bias-flip short setup"
Assert-Contains $text "def fastFlipLongSetup" "fast breakout bias-flip long setup"
Assert-Contains $text "def fastFlipShortArrow" "fast breakdown bias-flip short arrow"
Assert-Contains $text "def fastFlipLongArrow" "fast breakout bias-flip long arrow"
Assert-Contains $text "def shortContinuationPressure" "short 4/6 continuation pressure setup"
Assert-Contains $text "def longContinuationPressure" "long 4/6 continuation pressure setup"
Assert-Contains $text "def longSetupPulseReady" "long 5/6 setup pulse readiness"
Assert-Contains $text "def shortSetupPulseReady" "short 5/6 setup pulse readiness"
Assert-Contains $text "def setupPulseState" "recursive setup pulse state"
Assert-Contains $text "def setupPulseLongArrow = longSetupPulseReady and (setupPulseState[1] <= 0 or setupPulseState[1] >= setupPulseBars);" "long setup pulse state still exists for failsafe/debug bubbles"
Assert-Contains $text "def setupPulseShortArrow = shortSetupPulseReady and (setupPulseState[1] >= 0 or AbsValue(setupPulseState[1]) >= setupPulseBars);" "short setup pulse state still exists for failsafe/debug bubbles"
Assert-Before $text "def setupPulseState" "def setupPulseLongArrow" "setupPulseState must be defined before long setup pulse"
Assert-Before $text "def setupPulseState" "def setupPulseShortArrow" "setupPulseState must be defined before short setup pulse"
Assert-Contains $text "def setupCadenceSlot =" "raw setup cadence slot"
Assert-Contains $text "def rawSetupLongMarker = longSetupPulseReady and (!longSetupPulseReady[1] or setupCadenceSlot or lastVisibleBar);" "long raw setup marker uses first bar, cadence, and live endcap"
Assert-Contains $text "def rawSetupShortMarker = shortSetupPulseReady and (!shortSetupPulseReady[1] or setupCadenceSlot or lastVisibleBar);" "short raw setup marker uses first bar, cadence, and live endcap"
Assert-Contains $text "def rawSetupBubbleCadenceBars = Max(1, rawSetupBubbleBars);" "raw setup proof bubble cadence guard"
Assert-Contains $text "def rawSetupBubbleCadenceSlot =" "raw setup proof bubble cadence slot"
Assert-Contains $text "def rawSetupBubbleLong = longSetupPulseReady and (!longSetupPulseReady[1] or rawSetupBubbleCadenceSlot or lastVisibleBar);" "direct long raw setup bubble uses slower proof cadence"
Assert-Contains $text "def rawSetupBubbleShort = shortSetupPulseReady and (!shortSetupPulseReady[1] or rawSetupBubbleCadenceSlot or lastVisibleBar);" "direct short raw setup bubble uses slower proof cadence"
Assert-Contains $text "def shortContinuationArrow" "short continuation caution arrow"
Assert-Contains $text "def longContinuationArrow" "long continuation caution arrow"
Assert-Contains $text "def continuationAnchorLongArrow = showContinuationAnchorArrows and longContinuationPressure and longScore >= triggerThreshold;" "persistent long continuation anchor remains optional"
Assert-Contains $text "def continuationAnchorShortArrow = showContinuationAnchorArrows and shortContinuationPressure and shortScore >= triggerThreshold;" "persistent short continuation anchor remains optional"
Assert-Contains $text "def setupReviewLongEdge =" "balanced long setup review edge"
Assert-Contains $text "longScoreCrossEvent or !longSetupPulseReady[1] or (longScore >= 6 and longScore[1] < 6)" "long setup review fires on first 5/6 or 6/6 upgrade"
Assert-Contains $text "def setupReviewShortEdge =" "balanced short setup review edge"
Assert-Contains $text "shortScoreCrossEvent or !shortSetupPulseReady[1] or (shortScore >= 6 and shortScore[1] < 6)" "short setup review fires on first 5/6 or 6/6 upgrade"
Assert-Contains $text "def setupReviewCadenceBars = Max(1, setupReviewRefreshBars);" "setup review refresh cadence guard"
Assert-Contains $text "def setupReviewCadenceSlot =" "setup review refresh cadence slot"
Assert-Contains $text "def setupReviewLongDirectional = close > emaFast and close > close[1] and dFast >= 0;" "long setup review requires directional follow-through"
Assert-Contains $text "def setupReviewShortDirectional = close < emaFast and close < close[1] and dFast <= 0;" "short setup review requires directional follow-through"
Assert-Contains $text "def reviewChopLookback = Max(2, reviewChopLookbackBars);" "review chop lookback is guarded"
Assert-Contains $text "def reviewTrendTravel = AbsValue(close - close[reviewChopLookback]);" "review chop filter measures net travel"
Assert-Contains $text "def reviewTrendRange = Sum(candleTR, reviewChopLookback);" "review chop filter measures total travelled range"
Assert-Contains $text "def reviewTrendEfficiency = if reviewTrendRange > 0 then reviewTrendTravel / reviewTrendRange else 0;" "review chop filter computes directional efficiency"
Assert-Contains $text "def reviewEfficientMove = reviewTrendEfficiency >= minReviewTrendEfficiency;" "review chop filter requires efficient movement"
Assert-Contains $text "def reviewLongScoreDominant = longScore >= triggerThreshold and longScore - shortScore >= minReviewScoreSeparation;" "long review chop filter requires score dominance"
Assert-Contains $text "def reviewShortScoreDominant = shortScore >= triggerThreshold and shortScore - longScore >= minReviewScoreSeparation;" "short review chop filter requires score dominance"
Assert-Contains $text "def reviewContinuationBreakBars = Max(2, reviewContinuationBreakLookbackBars);" "review continuation break lookback is guarded"
Assert-Contains $text "def reviewLongContinuationScoreDominant = longScore >= standbyThreshold and longScore - shortScore >= minReviewContinuationScoreSeparation;" "long continuation review bypass requires score dominance"
Assert-Contains $text "def reviewShortContinuationScoreDominant = shortScore >= standbyThreshold and shortScore - longScore >= minReviewContinuationScoreSeparation;" "short continuation review bypass requires score dominance"
Assert-Contains $text "def reviewLongContinuationBreakOK = longContinuationPressure and reviewLongContinuationScoreDominant and close > Highest(high[1], reviewContinuationBreakBars);" "long continuation review bypass requires wider structure break"
Assert-Contains $text "def reviewShortContinuationBreakOK = shortContinuationPressure and reviewShortContinuationScoreDominant and close < Lowest(low[1], reviewContinuationBreakBars);" "short continuation review bypass requires wider structure break"
Assert-Contains $text "def reviewContinuationBlockedLong = longContinuationPressure and !reviewLongContinuationBreakOK;" "long continuation pullback block diagnostic"
Assert-Contains $text "def reviewContinuationBlockedShort = shortContinuationPressure and !reviewShortContinuationBreakOK;" "short continuation pullback block diagnostic"
Assert-Contains $text "def reviewFastBreakBars = Max(fastBreakLookback, reviewFastBreakLookbackBars);" "review fast-break lookback is guarded and no shorter than the raw fast break"
Assert-Contains $text "def reviewFastBreakoutOK = fastBreakoutConfirm and candleTR >= avgTR20 * reviewFastBreakTRFactor and close > Highest(high[1], reviewFastBreakBars);" "long review fast-break bypass requires stronger range and wider structure break"
Assert-Contains $text "def reviewFastBreakdownOK = fastBreakdownConfirm and candleTR >= avgTR20 * reviewFastBreakTRFactor and close < Lowest(low[1], reviewFastBreakBars);" "short review fast-break bypass requires stronger range and wider structure break"
Assert-Contains $text "def reviewFastBreakBlockedLong = fastBreakoutConfirm and !reviewFastBreakoutOK;" "long raw fast-break block diagnostic"
Assert-Contains $text "def reviewFastBreakBlockedShort = fastBreakdownConfirm and !reviewFastBreakdownOK;" "short raw fast-break block diagnostic"
Assert-Contains $text "def reviewTrendBreakBars = Max(2, reviewTrendBreakLookbackBars);" "review trend-structure lookback is guarded"
Assert-Contains $text "def reviewLongTrendCloseConfirmed = close > close[1] and close > emaFast and dFast >= 0 and close >= high - candleTR * reviewTrendCloseConfirmRatio;" "long efficient-score path needs directional candle close confirmation"
Assert-Contains $text "def reviewShortTrendCloseConfirmed = close < close[1] and close < emaFast and dFast <= 0 and close <= low + candleTR * reviewTrendCloseConfirmRatio;" "short efficient-score path needs directional candle close confirmation"
Assert-Contains $text "def reviewLongTrendBreakOK = reviewEfficientMove and reviewLongScoreDominant and close > emaSlow and close > Highest(high[1], reviewTrendBreakBars) and reviewLongTrendCloseConfirmed;" "long efficient-score path requires wider local structure break plus close confirmation"
Assert-Contains $text "def reviewShortTrendBreakOK = reviewEfficientMove and reviewShortScoreDominant and close < emaSlow and close < Lowest(low[1], reviewTrendBreakBars) and reviewShortTrendCloseConfirmed;" "short efficient-score path requires wider local structure break plus close confirmation"
Assert-Contains $text "def reviewTrendBlockedLong = reviewEfficientMove and reviewLongScoreDominant and close > emaSlow and !reviewLongTrendBreakOK;" "long efficient-score structure/close-confirm block diagnostic"
Assert-Contains $text "def reviewTrendBlockedShort = reviewEfficientMove and reviewShortScoreDominant and close < emaSlow and !reviewShortTrendBreakOK;" "short efficient-score structure/close-confirm block diagnostic"
Assert-Contains $text "def reviewLongRegimeOK =" "long review chop regime gate"
Assert-Contains $text "reviewFastBreakoutOK or" "long raw fast break cannot bypass review chop gate without stronger review fast-break proof"
Assert-Contains $text "reviewLongContinuationBreakOK or" "long continuation pressure cannot bypass review chop gate without a wider structure break"
Assert-Contains $text "reviewLongTrendBreakOK" "long review regime rejects efficient-score chop unless price also breaks local structure"
Assert-NoRegex $text "(?s)def reviewLongRegimeOK =(?:(?!;).)*fastBreakoutConfirm" "raw long fast-break confirm should not directly bypass the review chop gate"
Assert-NoRegex $text "(?s)def reviewLongRegimeOK =(?:(?!;).)*reviewEfficientMove" "raw long efficient-score condition should not directly bypass the structure guard"
Assert-NoRegex $text "(?s)def reviewLongRegimeOK =(?:(?!;).)*\n\s*longContinuationPressure\s+or" "raw long continuation pressure should not directly bypass the review chop gate"
Assert-NoRegex $text "(?s)def reviewLongRegimeOK =(?:(?!;).)*lowVolumeLongMomentum" "long low-volume momentum should not bypass review chop gate"
Assert-Contains $text "def reviewShortRegimeOK =" "short review chop regime gate"
Assert-Contains $text "reviewFastBreakdownOK or" "short raw fast break cannot bypass review chop gate without stronger review fast-break proof"
Assert-Contains $text "reviewShortContinuationBreakOK or" "short continuation pressure cannot bypass review chop gate without a wider structure break"
Assert-Contains $text "reviewShortTrendBreakOK" "short review regime rejects efficient-score chop unless price also breaks local structure"
Assert-NoRegex $text "(?s)def reviewShortRegimeOK =(?:(?!;).)*fastBreakdownConfirm" "raw short fast-break confirm should not directly bypass the review chop gate"
Assert-NoRegex $text "(?s)def reviewShortRegimeOK =(?:(?!;).)*reviewEfficientMove" "raw short efficient-score condition should not directly bypass the structure guard"
Assert-NoRegex $text "(?s)def reviewShortRegimeOK =(?:(?!;).)*\n\s*shortContinuationPressure\s+or" "raw short continuation pressure should not directly bypass the review chop gate"
Assert-NoRegex $text "(?s)def reviewShortRegimeOK =(?:(?!;).)*lowVolumeShortMomentum" "short low-volume momentum should not bypass review chop gate"
Assert-Contains $text "def setupReviewLongQualityRaw = longEntryConfirm or lowVolumeLongMomentum or longContinuationPressure or (longScore >= 6 and setupReviewLongDirectional);" "long sustained review quality source remains visible for diagnostics"
Assert-Contains $text "def setupReviewShortQualityRaw = shortEntryConfirm or lowVolumeShortMomentum or shortContinuationPressure or (shortScore >= 6 and setupReviewShortDirectional);" "short sustained review quality source remains visible for diagnostics"
Assert-Contains $text "def setupReviewLongQuality = setupReviewLongQualityRaw and reviewLongRegimeOK;" "long review quality is chop-filtered before visible arrows"
Assert-Contains $text "def setupReviewShortQuality = setupReviewShortQualityRaw and reviewShortRegimeOK;" "short review quality is chop-filtered before visible arrows"
Assert-Contains $text "def reviewChopBlockedLongSetup = setupReviewLongQualityRaw and !reviewLongRegimeOK;" "long setup-review chop block diagnostic"
Assert-Contains $text "def reviewChopBlockedShortSetup = setupReviewShortQualityRaw and !reviewShortRegimeOK;" "short setup-review chop block diagnostic"
Assert-Contains $text "def setupReviewLongEdgeQualified = setupReviewLongEdge and setupReviewLongQuality;" "long setup-review edge must pass quality"
Assert-Contains $text "def setupReviewShortEdgeQualified = setupReviewShortEdge and setupReviewShortQuality;" "short setup-review edge must pass quality"
Assert-Contains $text "def setupReviewLongRefresh = longSetupPulseReady and setupReviewCadenceSlot and setupReviewLongQuality;" "long sustained setup review refresh"
Assert-Contains $text "def setupReviewShortRefresh = shortSetupPulseReady and setupReviewCadenceSlot and setupReviewShortQuality;" "short sustained setup review refresh"
Assert-Contains $text "def scoreProbeLongReady = longSetupPulseReady and setupReviewCadenceSlot;" "long score-probe readiness bypasses review quality gate"
Assert-Contains $text "def scoreProbeShortReady = shortSetupPulseReady and setupReviewCadenceSlot;" "short score-probe readiness bypasses review quality gate"
Assert-Contains $text "def scoreProbeLongSignal = showScoreProbeArrows and scoreProbeLongReady;" "long score-probe arrow is gated by default-off visual toggle"
Assert-Contains $text "def scoreProbeShortSignal = showScoreProbeArrows and scoreProbeShortReady;" "short score-probe arrow is gated by default-off visual toggle"
Assert-NoRegex $text "(?m)^\s*def\s+real(?:Long|Short)Entry\s*=.*scoreProbe" "Score-probe diagnostics must not feed real trade entries"
Assert-NoRegex $text "(?m)^\s*def\s+(?:activeEntryPrice|lockedATR|activeDir|longTargetPrice|shortTargetPrice|longStopPrice|shortStopPrice)\s*=.*scoreProbe" "Score-probe diagnostics must not feed PT/SL tracking state"
Assert-NoRegex $text "(?m)^\s*def\s+dashboardTrigger(?:Long|Short)\s*=.*scoreProbe" "Score-probe diagnostics must not feed dashboard triggers"
Assert-NoRegex $text "(?s)Alert\s*\((?:(?!\);).)*scoreProbe" "Score-probe diagnostics must not feed alerts"
Assert-Contains $text "def realLongEntryReviewFlagRaw = if realLongEntry then 1 else 0;" "long real-entry raw review flag"
Assert-Contains $text "def realShortEntryReviewFlagRaw = if realShortEntry then 1 else 0;" "short real-entry raw review flag"
Assert-Contains $text "def realLongEntryReviewFlag = if IsNaN(realLongEntryReviewFlagRaw) then 0 else realLongEntryReviewFlagRaw;" "long real-entry review flag is NaN-safe"
Assert-Contains $text "def realShortEntryReviewFlag = if IsNaN(realShortEntryReviewFlagRaw) then 0 else realShortEntryReviewFlagRaw;" "short real-entry review flag is NaN-safe"
Assert-Contains $text "def realLongEntryForReviewRaw = realLongEntryReviewFlag == 1;" "long real-entry review raw boolean"
Assert-Contains $text "def realShortEntryForReviewRaw = realShortEntryReviewFlag == 1;" "short real-entry review raw boolean"
Assert-Contains $text "def reviewChopBlockedLongReal = realLongEntryForReviewRaw and !reviewLongRegimeOK;" "long real-entry chop block diagnostic"
Assert-Contains $text "def reviewChopBlockedShortReal = realShortEntryForReviewRaw and !reviewShortRegimeOK;" "short real-entry chop block diagnostic"
Assert-Contains $text "def realLongEntryForReview = realLongEntryForReviewRaw and reviewLongRegimeOK;" "long real-entry review boolean is chop-filtered"
Assert-Contains $text "def realShortEntryForReview = realShortEntryForReviewRaw and reviewShortRegimeOK;" "short real-entry review boolean is chop-filtered"
Assert-Contains $text "def reviewChopBlockedLong = reviewChopBlockedLongSetup or reviewChopBlockedLongReal;" "long chop block count includes setup and real review sources"
Assert-Contains $text "def reviewChopBlockedShort = reviewChopBlockedShortSetup or reviewChopBlockedShortReal;" "short chop block count includes setup and real review sources"
Assert-Contains $text "def reviewLongSetupSignalRaw = showSetupReviewArrows and (setupReviewLongEdgeQualified or setupReviewLongRefresh);" "long setup review raw signal includes qualified edge plus slow refresh"
Assert-Contains $text "def reviewShortSetupSignalRaw = showSetupReviewArrows and (setupReviewShortEdgeQualified or setupReviewShortRefresh);" "short setup review raw signal includes qualified edge plus slow refresh"
Assert-Contains $text "def reviewLongSetupSignalFlagRaw = if reviewLongSetupSignalRaw then 1 else 0;" "long setup-review raw flag"
Assert-Contains $text "def reviewShortSetupSignalFlagRaw = if reviewShortSetupSignalRaw then 1 else 0;" "short setup-review raw flag"
Assert-Contains $text "def reviewLongSetupSignalFlag = if IsNaN(reviewLongSetupSignalFlagRaw) then 0 else reviewLongSetupSignalFlagRaw;" "long setup-review flag is NaN-safe"
Assert-Contains $text "def reviewShortSetupSignalFlag = if IsNaN(reviewShortSetupSignalFlagRaw) then 0 else reviewShortSetupSignalFlagRaw;" "short setup-review flag is NaN-safe"
Assert-Contains $text "def reviewLongSetupSignal = reviewLongSetupSignalFlag == 1;" "long setup review safe signal"
Assert-Contains $text "def reviewShortSetupSignal = reviewShortSetupSignalFlag == 1;" "short setup review safe signal"
Assert-Contains $text "def visualLongSetupReady = reviewLongSetupSignal;" "setup review drives default long visual arrows without raw cadence"
Assert-Contains $text "def visualShortSetupReady = reviewShortSetupSignal;" "setup review drives default short visual arrows without raw cadence"
Assert-Contains $text "def reviewLongCandidate = realLongEntryForReview or reviewLongSetupSignal;" "long review candidate is assembled before mixed-direction filter"
Assert-Contains $text "def reviewShortCandidate = realShortEntryForReview or reviewShortSetupSignal;" "short review candidate is assembled before mixed-direction filter"
Assert-Contains $text "def reviewConflictBars = Max(2, reviewConflictLookbackBars);" "mixed-direction conflict lookback is guarded"
Assert-Contains $text "def reviewBothSidesRecentLong = reviewConflictFilterEnabled and reviewLongCandidate and Sum(if reviewShortCandidate then 1 else 0, reviewConflictBars) > 0;" "long mixed-direction conflict detects recent opposite-side candidates"
Assert-Contains $text "def reviewBothSidesRecentShort = reviewConflictFilterEnabled and reviewShortCandidate and Sum(if reviewLongCandidate then 1 else 0, reviewConflictBars) > 0;" "short mixed-direction conflict detects recent opposite-side candidates"
Assert-Contains $text "def reviewBothSidesRecent = reviewBothSidesRecentLong or reviewBothSidesRecentShort;" "mixed-direction conflict diagnostic combines both sides"
Assert-Contains $text "def reviewConflictEfficientMove = reviewTrendEfficiency >= minConflictEscapeTrendEfficiency;" "mixed-conflict escape uses stricter directional efficiency"
Assert-Contains $text "def reviewLongConflictScoreDominant = longScore >= triggerThreshold and longScore - shortScore >= minConflictEscapeScoreSeparation;" "long mixed-conflict escape uses stricter score dominance"
Assert-Contains $text "def reviewShortConflictScoreDominant = shortScore >= triggerThreshold and shortScore - longScore >= minConflictEscapeScoreSeparation;" "short mixed-conflict escape uses stricter score dominance"
Assert-Contains $text "def reviewLongConflictEscape = (reviewFastBreakoutOK and reviewLongConflictScoreDominant) or (reviewConflictEfficientMove and reviewLongConflictScoreDominant and close > emaSlow and close > vwapLine);" "long conflict escape requires review fast-break proof plus score dominance or stronger efficient directional structure"
Assert-Contains $text "def reviewShortConflictEscape = (reviewFastBreakdownOK and reviewShortConflictScoreDominant) or (reviewConflictEfficientMove and reviewShortConflictScoreDominant and close < emaSlow and close < vwapLine);" "short conflict escape requires review fast-break proof plus score dominance or stronger efficient directional structure"
Assert-NoRegex $text "(?s)def reviewLongConflictEscape =(?:(?!;).)*fastBreakoutConfirm" "raw long fast-break confirm must not directly escape mixed-direction chop"
Assert-NoRegex $text "(?s)def reviewShortConflictEscape =(?:(?!;).)*fastBreakdownConfirm" "raw short fast-break confirm must not directly escape mixed-direction chop"
Assert-NoRegex $text "(?s)def reviewLongConflictEscape =(?:(?!;).)*longContinuationPressure" "long continuation pressure must not auto-escape mixed-direction chop"
Assert-NoRegex $text "(?s)def reviewShortConflictEscape =(?:(?!;).)*shortContinuationPressure" "short continuation pressure must not auto-escape mixed-direction chop"
Assert-Contains $text "def reviewConflictEscapedLong = reviewBothSidesRecentLong and reviewLongConflictEscape;" "long mixed-direction escape diagnostic"
Assert-Contains $text "def reviewConflictEscapedShort = reviewBothSidesRecentShort and reviewShortConflictEscape;" "short mixed-direction escape diagnostic"
Assert-Contains $text "def reviewConflictBlockedLong = reviewBothSidesRecentLong and !reviewLongConflictEscape;" "long mixed-direction review candidate is blocked in chop"
Assert-Contains $text "def reviewConflictBlockedShort = reviewBothSidesRecentShort and !reviewShortConflictEscape;" "short mixed-direction review candidate is blocked in chop"
Assert-Contains $text "def reviewLongRawPressure = setupReviewLongQualityRaw or realLongEntryForReviewRaw;" "long raw pressure keeps opposite-side chop memory before filters suppress candidates"
Assert-Contains $text "def reviewShortRawPressure = setupReviewShortQualityRaw or realShortEntryForReviewRaw;" "short raw pressure keeps opposite-side chop memory before filters suppress candidates"
Assert-Contains $text "def reviewPressureConflictBars = Max(reviewConflictBars, reviewPressureConflictLookbackBars);" "raw-pressure conflict lookback is guarded and at least as wide as candidate conflict"
Assert-Contains $text "def reviewPressureConflictLong = reviewConflictFilterEnabled and reviewLongCandidate and Sum(if reviewShortRawPressure then 1 else 0, reviewPressureConflictBars) > 0;" "long raw-pressure conflict detects recent suppressed short pressure"
Assert-Contains $text "def reviewPressureConflictShort = reviewConflictFilterEnabled and reviewShortCandidate and Sum(if reviewLongRawPressure then 1 else 0, reviewPressureConflictBars) > 0;" "short raw-pressure conflict detects recent suppressed long pressure"
Assert-Contains $text "def reviewPressureConflictEfficientMove = reviewTrendEfficiency >= minPressureConflictEscapeTrendEfficiency;" "raw-pressure conflict escape needs stronger trend efficiency"
Assert-Contains $text "def reviewLongPressureConflictScoreDominant = longScore >= triggerThreshold and longScore - shortScore >= minPressureConflictEscapeScoreSeparation;" "long raw-pressure conflict escape needs stronger score dominance"
Assert-Contains $text "def reviewShortPressureConflictScoreDominant = shortScore >= triggerThreshold and shortScore - longScore >= minPressureConflictEscapeScoreSeparation;" "short raw-pressure conflict escape needs stronger score dominance"
Assert-Contains $text "def reviewLongPressureConflictEscape = (reviewFastBreakoutOK and reviewLongPressureConflictScoreDominant) or (reviewPressureConflictEfficientMove and reviewLongPressureConflictScoreDominant and reviewLongTrendBreakOK and close > vwapLine);" "long raw-pressure conflict only escapes on score-confirmed strong fast break or confirmed trend structure"
Assert-Contains $text "def reviewShortPressureConflictEscape = (reviewFastBreakdownOK and reviewShortPressureConflictScoreDominant) or (reviewPressureConflictEfficientMove and reviewShortPressureConflictScoreDominant and reviewShortTrendBreakOK and close < vwapLine);" "short raw-pressure conflict only escapes on score-confirmed strong fast break or confirmed trend structure"
Assert-Contains $text "def reviewPressureConflictBlockedLong = reviewPressureConflictLong and !reviewLongPressureConflictEscape;" "long raw-pressure conflict blocks chop flips"
Assert-Contains $text "def reviewPressureConflictBlockedShort = reviewPressureConflictShort and !reviewShortPressureConflictEscape;" "short raw-pressure conflict blocks chop flips"
Assert-Before $text "def setupReviewLongEdge" "def reviewLongSetupSignalRaw" "long setup edge must be defined before long setup review signal"
Assert-Before $text "def setupReviewShortEdge" "def reviewShortSetupSignalRaw" "short setup edge must be defined before short setup review signal"
Assert-Before $text "def setupReviewLongDirectional" "def setupReviewLongQuality" "long setup review directional state must be defined before quality"
Assert-Before $text "def setupReviewShortDirectional" "def setupReviewShortQuality" "short setup review directional state must be defined before quality"
Assert-Before $text "def reviewTrendEfficiency" "def reviewLongRegimeOK" "trend efficiency must be defined before long regime gate"
Assert-Before $text "def reviewTrendEfficiency" "def reviewShortRegimeOK" "trend efficiency must be defined before short regime gate"
Assert-Before $text "def reviewFastBreakoutOK" "def reviewLongRegimeOK" "long review fast-break proof must be defined before long regime gate"
Assert-Before $text "def reviewFastBreakdownOK" "def reviewShortRegimeOK" "short review fast-break proof must be defined before short regime gate"
Assert-Before $text "def reviewLongContinuationBreakOK" "def reviewLongRegimeOK" "long review continuation break must be defined before long regime gate"
Assert-Before $text "def reviewShortContinuationBreakOK" "def reviewShortRegimeOK" "short review continuation break must be defined before short regime gate"
Assert-Before $text "def reviewLongTrendBreakOK" "def reviewLongRegimeOK" "long review trend-structure proof must be defined before long regime gate"
Assert-Before $text "def reviewShortTrendBreakOK" "def reviewShortRegimeOK" "short review trend-structure proof must be defined before short regime gate"
Assert-Before $text "def setupReviewLongQualityRaw" "def setupReviewLongQuality = setupReviewLongQualityRaw" "raw long setup review quality must be defined before chop-filtered quality"
Assert-Before $text "def setupReviewShortQualityRaw" "def setupReviewShortQuality = setupReviewShortQualityRaw" "raw short setup review quality must be defined before chop-filtered quality"
Assert-Before $text "def setupReviewLongQualityRaw" "def reviewChopBlockedLongSetup" "raw long setup review quality must be defined before setup chop block"
Assert-Before $text "def setupReviewShortQualityRaw" "def reviewChopBlockedShortSetup" "raw short setup review quality must be defined before setup chop block"
Assert-Before $text "def setupReviewLongQuality" "def setupReviewLongEdgeQualified" "long setup review quality must be defined before qualified edge"
Assert-Before $text "def setupReviewShortQuality" "def setupReviewShortEdgeQualified" "short setup review quality must be defined before qualified edge"
Assert-Before $text "def setupReviewLongEdgeQualified" "def reviewLongSetupSignalRaw" "long setup qualified edge must be defined before long setup review signal"
Assert-Before $text "def setupReviewShortEdgeQualified" "def reviewShortSetupSignalRaw" "short setup qualified edge must be defined before short setup review signal"
Assert-Before $text "def setupReviewCadenceSlot" "def setupReviewLongRefresh" "setup review cadence must be defined before long refresh"
Assert-Before $text "def setupReviewCadenceSlot" "def setupReviewShortRefresh" "setup review cadence must be defined before short refresh"
Assert-Before $text "def setupReviewCadenceSlot" "def scoreProbeLongReady" "setup review cadence must be defined before long score-probe readiness"
Assert-Before $text "def setupReviewCadenceSlot" "def scoreProbeShortReady" "setup review cadence must be defined before short score-probe readiness"
Assert-Before $text "def scoreProbeLongReady" "def scoreProbeLongSignal" "long score-probe readiness must be defined before visual signal"
Assert-Before $text "def scoreProbeShortReady" "def scoreProbeShortSignal" "short score-probe readiness must be defined before visual signal"
Assert-Before $text "def reviewLongSetupSignalRaw" "def reviewLongSetupSignal = reviewLongSetupSignalFlag == 1;" "long setup review raw signal must be sanitized before use"
Assert-Before $text "def reviewShortSetupSignalRaw" "def reviewShortSetupSignal = reviewShortSetupSignalFlag == 1;" "short setup review raw signal must be sanitized before use"
Assert-Before $text "def realLongEntryForReviewRaw" "def realLongEntryForReview = realLongEntryForReviewRaw and reviewLongRegimeOK;" "raw real long review signal must be defined before filtered real review signal"
Assert-Before $text "def realShortEntryForReviewRaw" "def realShortEntryForReview = realShortEntryForReviewRaw and reviewShortRegimeOK;" "raw real short review signal must be defined before filtered real review signal"
Assert-Before $text "def reviewChopBlockedLongSetup" "def reviewChopBlockedLong = reviewChopBlockedLongSetup or reviewChopBlockedLongReal;" "long setup chop block must be defined before combined chop count"
Assert-Before $text "def reviewChopBlockedLongReal" "def reviewChopBlockedLong = reviewChopBlockedLongSetup or reviewChopBlockedLongReal;" "long real chop block must be defined before combined chop count"
Assert-Before $text "def reviewChopBlockedShortSetup" "def reviewChopBlockedShort = reviewChopBlockedShortSetup or reviewChopBlockedShortReal;" "short setup chop block must be defined before combined chop count"
Assert-Before $text "def reviewChopBlockedShortReal" "def reviewChopBlockedShort = reviewChopBlockedShortSetup or reviewChopBlockedShortReal;" "short real chop block must be defined before combined chop count"
Assert-Before $text "def reviewLongCandidate" "def reviewBothSidesRecentLong" "long candidate must be defined before mixed-direction detection"
Assert-Before $text "def reviewShortCandidate" "def reviewBothSidesRecentShort" "short candidate must be defined before mixed-direction detection"
Assert-Before $text "def reviewBothSidesRecentLong" "def reviewConflictBlockedLong" "long mixed-direction detection must be defined before block"
Assert-Before $text "def reviewBothSidesRecentShort" "def reviewConflictBlockedShort" "short mixed-direction detection must be defined before block"
Assert-Before $text "def setupReviewLongQualityRaw" "def reviewLongRawPressure" "raw long quality must be defined before raw-pressure memory"
Assert-Before $text "def setupReviewShortQualityRaw" "def reviewShortRawPressure" "raw short quality must be defined before raw-pressure memory"
Assert-Before $text "def realLongEntryForReviewRaw" "def reviewLongRawPressure" "raw real long review must feed raw-pressure memory"
Assert-Before $text "def realShortEntryForReviewRaw" "def reviewShortRawPressure" "raw real short review must feed raw-pressure memory"
Assert-Before $text "def reviewConflictBars" "def reviewPressureConflictBars" "candidate conflict lookback guard must be defined before raw-pressure guard"
Assert-Before $text "def reviewShortRawPressure" "def reviewPressureConflictLong" "short raw pressure must be defined before long raw-pressure conflict"
Assert-Before $text "def reviewLongRawPressure" "def reviewPressureConflictShort" "long raw pressure must be defined before short raw-pressure conflict"
Assert-Before $text "def reviewPressureConflictEfficientMove" "def reviewLongPressureConflictEscape" "raw-pressure efficiency must be defined before long escape"
Assert-Before $text "def reviewPressureConflictEfficientMove" "def reviewShortPressureConflictEscape" "raw-pressure efficiency must be defined before short escape"
Assert-Before $text "def reviewPressureConflictBlockedLong" "def reviewLongSignal = reviewLongCandidate and !reviewConflictBlockedLong and !reviewPressureConflictBlockedLong;" "long raw-pressure block must be defined before final long review signal"
Assert-Before $text "def reviewPressureConflictBlockedShort" "def reviewShortSignal = reviewShortCandidate and !reviewConflictBlockedShort and !reviewPressureConflictBlockedShort;" "short raw-pressure block must be defined before final short review signal"
Assert-Before $text "def reviewConflictEfficientMove" "def reviewLongConflictEscape" "stricter mixed-conflict efficiency must be defined before long escape"
Assert-Before $text "def reviewConflictEfficientMove" "def reviewShortConflictEscape" "stricter mixed-conflict efficiency must be defined before short escape"
Assert-Before $text "def reviewFastBreakoutOK" "def reviewLongConflictEscape" "long review fast-break proof must be defined before long mixed-conflict escape"
Assert-Before $text "def reviewFastBreakdownOK" "def reviewShortConflictEscape" "short review fast-break proof must be defined before short mixed-conflict escape"
Assert-Before $text "def reviewLongConflictScoreDominant" "def reviewLongConflictEscape" "stricter long mixed-conflict score dominance must be defined before long escape"
Assert-Before $text "def reviewShortConflictScoreDominant" "def reviewShortConflictEscape" "stricter short mixed-conflict score dominance must be defined before short escape"
Assert-Before $text "def reviewConflictBlockedLong" "def reviewLongSignal = reviewLongCandidate and !reviewConflictBlockedLong and !reviewPressureConflictBlockedLong;" "long mixed-direction block must be defined before final long review signal"
Assert-Before $text "def reviewConflictBlockedShort" "def reviewShortSignal = reviewShortCandidate and !reviewConflictBlockedShort and !reviewPressureConflictBlockedShort;" "short mixed-direction block must be defined before final short review signal"
Assert-Before $text "def scoreProbeLongSignal" "plot ScoreProbeLongArrowV0542" "long score-probe signal must be defined before plot"
Assert-Before $text "def scoreProbeShortSignal" "plot ScoreProbeShortArrowV0542" "short score-probe signal must be defined before plot"
Assert-Contains $text "def realLongEntry = newLongEntry or practicalLongArrow or fastFlipLongArrow or longContinuationArrow;" "real long entry excludes visual-only setup pulse"
Assert-Contains $text "def realShortEntry = newShortEntry or practicalShortArrow or fastFlipShortArrow or shortContinuationArrow;" "real short entry excludes visual-only setup pulse"
Assert-True -Condition (-not $text.Contains("def spamDiagMode = yes;")) -Message "Hardwired spam diagnostic mode is still enabled"
Assert-True -Condition (-not $text.Contains("def spamDiagLong")) -Message "Spam diagnostic long signal is still present"
Assert-True -Condition (-not $text.Contains("def spamDiagShort")) -Message "Spam diagnostic short signal is still present"
Assert-Contains $text "def reviewLongSignal = reviewLongCandidate and !reviewConflictBlockedLong and !reviewPressureConflictBlockedLong;" "balanced long review signal is NaN-safe and raw-pressure conflict filtered"
Assert-Contains $text "def reviewShortSignal = reviewShortCandidate and !reviewConflictBlockedShort and !reviewPressureConflictBlockedShort;" "balanced short review signal is NaN-safe and raw-pressure conflict filtered"
Assert-Contains $text "def reviewVisualSpacingBars = Max(1, reviewVisualMinBars);" "visual review throttle cadence guard"
Assert-Contains $text "def reviewVisualReady = reviewVisualState[1] == 0 or AbsValue(reviewVisualState[1]) >= reviewVisualSpacingBars;" "visual review throttle waits before repeated arrows"
Assert-Contains $text "def reviewVisualState =" "recursive visual review throttle state"
Assert-Contains $text "if reviewLongSignal and (reviewVisualState[1] == 0 or AbsValue(reviewVisualState[1]) >= reviewVisualSpacingBars) then 1" "long visual review signal can reset throttle without forward self-reference"
Assert-Contains $text "else if reviewShortSignal and (reviewVisualState[1] == 0 or AbsValue(reviewVisualState[1]) >= reviewVisualSpacingBars) then -1" "short visual review signal can reset throttle without forward self-reference"
Assert-Contains $text "def visibleLongSignal = reviewLongSignal and reviewVisualState == 1 and reviewVisualState[1] != 1;" "visible long signal uses throttled review signal"
Assert-Contains $text "def visibleShortSignal = reviewShortSignal and reviewVisualState == -1 and reviewVisualState[1] != -1;" "visible short signal uses throttled review signal"
Assert-Contains $text "def setupLongRecentCount = Sum(if longSetupPulseReady then 1 else 0, reviewDebugLookbackBars);" "recent long setup debug count"
Assert-Contains $text "def setupShortRecentCount = Sum(if shortSetupPulseReady then 1 else 0, reviewDebugLookbackBars);" "recent short setup debug count"
Assert-Contains $text "def reviewLongRecentCount = Sum(if reviewLongSignal then 1 else 0, reviewDebugLookbackBars);" "recent long review debug count"
Assert-Contains $text "def reviewShortRecentCount = Sum(if reviewShortSignal then 1 else 0, reviewDebugLookbackBars);" "recent short review debug count"
Assert-Contains $text "def visibleLongRecentCount = Sum(if visibleLongSignal then 1 else 0, reviewDebugLookbackBars);" "recent visible long debug count"
Assert-Contains $text "def visibleShortRecentCount = Sum(if visibleShortSignal then 1 else 0, reviewDebugLookbackBars);" "recent visible short debug count"
Assert-Contains $text "def reviewChopBlockedLongRecentCount = Sum(if reviewChopBlockedLong then 1 else 0, reviewDebugLookbackBars);" "recent long chop-block debug count"
Assert-Contains $text "def reviewChopBlockedShortRecentCount = Sum(if reviewChopBlockedShort then 1 else 0, reviewDebugLookbackBars);" "recent short chop-block debug count"
Assert-Contains $text "def reviewContinuationBlockedLongRecentCount = Sum(if reviewContinuationBlockedLong then 1 else 0, reviewDebugLookbackBars);" "recent long continuation pullback block debug count"
Assert-Contains $text "def reviewContinuationBlockedShortRecentCount = Sum(if reviewContinuationBlockedShort then 1 else 0, reviewDebugLookbackBars);" "recent short continuation pullback block debug count"
Assert-Contains $text "def reviewFastBreakBlockedLongRecentCount = Sum(if reviewFastBreakBlockedLong then 1 else 0, reviewDebugLookbackBars);" "recent long raw fast-break block debug count"
Assert-Contains $text "def reviewFastBreakBlockedShortRecentCount = Sum(if reviewFastBreakBlockedShort then 1 else 0, reviewDebugLookbackBars);" "recent short raw fast-break block debug count"
Assert-Contains $text "def reviewTrendBlockedLongRecentCount = Sum(if reviewTrendBlockedLong then 1 else 0, reviewDebugLookbackBars);" "recent long no-structure block debug count"
Assert-Contains $text "def reviewTrendBlockedShortRecentCount = Sum(if reviewTrendBlockedShort then 1 else 0, reviewDebugLookbackBars);" "recent short no-structure block debug count"
Assert-Contains $text "def reviewBothSidesLongRecentCount = Sum(if reviewBothSidesRecentLong then 1 else 0, reviewDebugLookbackBars);" "recent long mixed-direction detection debug count"
Assert-Contains $text "def reviewBothSidesShortRecentCount = Sum(if reviewBothSidesRecentShort then 1 else 0, reviewDebugLookbackBars);" "recent short mixed-direction detection debug count"
Assert-Contains $text "def reviewConflictEscapedLongRecentCount = Sum(if reviewConflictEscapedLong then 1 else 0, reviewDebugLookbackBars);" "recent long mixed-direction escape debug count"
Assert-Contains $text "def reviewConflictEscapedShortRecentCount = Sum(if reviewConflictEscapedShort then 1 else 0, reviewDebugLookbackBars);" "recent short mixed-direction escape debug count"
Assert-Contains $text "def reviewConflictBlockedLongRecentCount = Sum(if reviewConflictBlockedLong then 1 else 0, reviewDebugLookbackBars);" "recent long mixed-direction block debug count"
Assert-Contains $text "def reviewConflictBlockedShortRecentCount = Sum(if reviewConflictBlockedShort then 1 else 0, reviewDebugLookbackBars);" "recent short mixed-direction block debug count"
Assert-Contains $text "def reviewPressureConflictBlockedLongRecentCount = Sum(if reviewPressureConflictBlockedLong then 1 else 0, reviewDebugLookbackBars);" "recent long raw-pressure flip block debug count"
Assert-Contains $text "def reviewPressureConflictBlockedShortRecentCount = Sum(if reviewPressureConflictBlockedShort then 1 else 0, reviewDebugLookbackBars);" "recent short raw-pressure flip block debug count"
Assert-Contains $text "def scoreProbeLongRecentCount = Sum(if scoreProbeLongReady then 1 else 0, reviewDebugLookbackBars);" "recent long score-probe readiness debug count"
Assert-Contains $text "def scoreProbeShortRecentCount = Sum(if scoreProbeShortReady then 1 else 0, reviewDebugLookbackBars);" "recent short score-probe readiness debug count"
Assert-Contains $text "def reviewLongAnyLoaded = HighestAll(if reviewLongSignal then 1 else 0);" "any-loaded long review debug count"
Assert-Contains $text "def reviewShortAnyLoaded = HighestAll(if reviewShortSignal then 1 else 0);" "any-loaded short review debug count"
Assert-Before $text "def reviewLongSetupSignal" "def reviewLongSignal" "long setup review signal must be defined before balanced long review signal"
Assert-Before $text "def reviewShortSetupSignal" "def reviewShortSignal" "short setup review signal must be defined before balanced short review signal"
Assert-Before $text "def reviewLongSignal" "def reviewVisualState" "review long signal must be defined before visual throttle state"
Assert-Before $text "def reviewShortSignal" "def reviewVisualState" "review short signal must be defined before visual throttle state"
Assert-Before $text "def reviewVisualState" "def reviewVisualReady" "visual throttle ready label must not be forward-referenced by state"
Assert-Before $text "def reviewVisualState" "def visibleLongSignal" "visual throttle state must be defined before visible long signal"
Assert-Before $text "def reviewVisualState" "def visibleShortSignal" "visual throttle state must be defined before visible short signal"
Assert-Before $text "def reviewLongSignal" "def reviewLongRecentCount" "review long signal must be defined before debug count"
Assert-Before $text "def reviewShortSignal" "def reviewShortRecentCount" "review short signal must be defined before debug count"
Assert-Contains $text "def arrowMarkerLong = visibleLongSignal;" "compact long marker follows visible long signal"
Assert-Contains $text "def arrowMarkerShort = visibleShortSignal;" "compact short marker follows visible short signal"
Assert-Contains $text "def dashboardContLong = longContinuationArrow;" "CONT LONG dashboard uses edge-based continuation only"
Assert-Contains $text "def dashboardContShort = shortContinuationArrow;" "CONT SHORT dashboard uses edge-based continuation only"
Assert-Contains $text "def dashboardTriggerLong = visibleLongSignal;" "long dashboard trigger follows visible throttled arrows"
Assert-Contains $text "def dashboardTriggerShort = visibleShortSignal;" "short dashboard trigger follows visible throttled arrows"
Assert-Contains $text "def markerRequiredLong = dashboardTriggerLong;" "long marker required by dashboard trigger"
Assert-Contains $text "def markerRequiredShort = dashboardTriggerShort;" "short marker required by dashboard trigger"
Assert-Contains $text "def markerContractFail =" "trigger/marker contract failure boolean"
Assert-Contains $text "def longSignalCaution = longScore < triggerThreshold or longTradeCaution or fastFlipLongArrow or longContinuationArrow or reviewLongSetupSignal;" "setup review long is marked caution"
Assert-Contains $text "def shortSignalCaution = shortScore < triggerThreshold or shortTradeCaution or fastFlipShortArrow or shortContinuationArrow or reviewShortSetupSignal;" "setup review short is marked caution"
Assert-Contains $text '"FLIP S "' "fast flip short signal bubble"
Assert-Contains $text '"FLIP L "' "fast flip long signal bubble"
Assert-Contains $text '"CONT S "' "continuation short signal bubble"
Assert-Contains $text '"CONT L "' "continuation long signal bubble"
Assert-Contains $text '"SETUP S "' "setup pulse short signal bubble"
Assert-Contains $text '"SETUP L "' "setup pulse long signal bubble"
Assert-Contains $text "plot MarkerLongDotV0513 =" "fresh long marker dot fallback plot"
Assert-Contains $text "plot MarkerShortDotV0513 =" "fresh short marker dot fallback plot"
Assert-Contains $text "if arrowMarkerLong then low - compactMarkerOff else Double.NaN;" "long marker dot is driven directly by visible signal"
Assert-Contains $text "if arrowMarkerShort then high + compactMarkerOff else Double.NaN;" "short marker dot is driven directly by visible signal"
Assert-Contains $text "MarkerLongDotV0513.SetPaintingStrategy(PaintingStrategy.POINTS);" "long marker dot uses points instead of arrow painting"
Assert-Contains $text "MarkerShortDotV0513.SetPaintingStrategy(PaintingStrategy.POINTS);" "short marker dot uses points instead of arrow painting"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+RawSetupLongArrowV05(19|20|21|22|23|24)\b").Count -eq 0) -Message "Raw setup arrow plot should not remain as a default arrow layer"
Assert-True -Condition ([regex]::Matches($text, "(?m)^\s*plot\s+RawSetupShortArrowV05(19|20|21|22|23|24)\b").Count -eq 0) -Message "Raw setup arrow plot should not remain as a default arrow layer"
Assert-Contains $text "plot ReviewLongArrowV0542 =" "fresh working-style long review arrow plot"
Assert-Contains $text "plot ReviewShortArrowV0542 =" "fresh working-style short review arrow plot"
Assert-Contains $text "if showReviewSignalArrows and visibleLongSignal then low - reviewArrowOff else Double.NaN;" "review long arrow uses risk-aware offset beyond the stop bubble"
Assert-Contains $text "if showReviewSignalArrows and visibleShortSignal then high + reviewArrowOff else Double.NaN;" "review short arrow uses risk-aware offset beyond the stop bubble"
Assert-Contains $text "ReviewLongArrowV0542.SetPaintingStrategy(PaintingStrategy.ARROW_UP);" "review long arrow uses ARROW_UP"
Assert-Contains $text "ReviewShortArrowV0542.SetPaintingStrategy(PaintingStrategy.ARROW_DOWN);" "review short arrow uses ARROW_DOWN"
Assert-Contains $text "ReviewLongArrowV0542.AssignValueColor(Color.MAGENTA);" "review long arrow uses AssignValueColor"
Assert-Contains $text "ReviewShortArrowV0542.AssignValueColor(Color.CYAN);" "review short arrow uses AssignValueColor"
Assert-Contains $text "ReviewLongArrowV0542.SetLineWeight(5);" "review long arrow line weight"
Assert-Contains $text "ReviewShortArrowV0542.SetLineWeight(5);" "review short arrow line weight"
Assert-Contains $text "plot ScoreProbeLongArrowV0542 =" "fresh long score-probe diagnostic arrow plot"
Assert-Contains $text "plot ScoreProbeShortArrowV0542 =" "fresh short score-probe diagnostic arrow plot"
Assert-Contains $text "if scoreProbeLongSignal and !reviewLongSignal then low - off * 2 else Double.NaN;" "long score-probe only appears when review gate is silent"
Assert-Contains $text "if scoreProbeShortSignal and !reviewShortSignal then high + off * 2 else Double.NaN;" "short score-probe only appears when review gate is silent"
Assert-Contains $text "ScoreProbeLongArrowV0542.SetPaintingStrategy(PaintingStrategy.ARROW_UP);" "long score-probe uses ARROW_UP"
Assert-Contains $text "ScoreProbeShortArrowV0542.SetPaintingStrategy(PaintingStrategy.ARROW_DOWN);" "short score-probe uses ARROW_DOWN"
Assert-Contains $text "ScoreProbeLongArrowV0542.AssignValueColor(Color.GREEN);" "long score-probe uses distinct color"
Assert-Contains $text "ScoreProbeShortArrowV0542.AssignValueColor(Color.RED);" "short score-probe uses distinct color"
Assert-Contains $text "ScoreProbeLongArrowV0542.SetLineWeight(3);" "long score-probe line weight"
Assert-Contains $text "ScoreProbeShortArrowV0542.SetLineWeight(3);" "short score-probe line weight"
Assert-True -Condition (-not [regex]::IsMatch($text, "(?m)^\s*plot\s+Review(?:Long|Short)ArrowV05(?:2[3456789]|3[0123456789]|4[01])\b")) -Message "Old v0.5.23-v0.5.41 review arrow plot names should not remain"
Assert-True -Condition (-not [regex]::IsMatch($text, "(?m)^\s*plot\s+ScoreProbe(?:Long|Short)ArrowV05(?:2[456789]|3[0123456789]|4[01])\b")) -Message "Old v0.5.24-v0.5.41 score-probe arrow plot names should not remain"
Assert-True -Condition (-not [regex]::IsMatch($text, 'Review(?:Long|Short)ArrowV0542\.Hide(?:Bubble|Title)?\(')) -Message "Working-style review arrow plots should not be hidden by Hide/HideBubble/HideTitle calls"
Assert-Contains $text "    showSignalBubbles and arrowMarkerLong," "compact long marker bubble is optional"
Assert-Contains $text "    showSignalBubbles and arrowMarkerShort," "compact short marker bubble is optional"
Assert-True -Condition (-not [regex]::IsMatch($text, "AddChartBubble\(\s*arrowMarker(?:Long|Short)\s*,")) -Message "Compact marker bubbles should not be hardwired on"
Assert-True -Condition (-not $text.Contains("showArrowMarkerBubbles and arrowMarkerLong")) -Message "Long marker bubble still depends on showArrowMarkerBubbles"
Assert-True -Condition (-not $text.Contains("showArrowMarkerBubbles and arrowMarkerShort")) -Message "Short marker bubble still depends on showArrowMarkerBubbles"
Assert-Contains $text '"L"' "compact long marker label"
Assert-Contains $text '"S"' "compact short marker label"
Assert-Contains $text "Color.MAGENTA" "compact long marker color"
Assert-Contains $text "Color.CYAN" "compact short marker color"
Assert-Contains $text '"MARKER: NONE"' "dashboard marker state label"
Assert-Contains $text 'AddLabel(yes, "BUILD: v0.5.42 RISK SPACE", Color.BLACK);' "always-visible build version dashboard label"
Assert-Contains $text 'AddLabel(arrowMarkerLong and arrowMarkerShort, "MARKER: BOTH", if markerContractFail then Color.RED else Color.GRAY);' "static marker both label"
Assert-Contains $text 'AddLabel(arrowMarkerLong and !arrowMarkerShort, "MARKER: L", if markerContractFail then Color.RED else Color.MAGENTA);' "static marker long label"
Assert-Contains $text 'AddLabel(!arrowMarkerLong and arrowMarkerShort, "MARKER: S", if markerContractFail then Color.RED else Color.CYAN);' "static marker short label"
Assert-Contains $text 'AddLabel(!arrowMarkerLong and !arrowMarkerShort, "MARKER: NONE", if markerContractFail then Color.RED else Color.GRAY);' "static marker none label"
Assert-Contains $text 'AddLabel(markerContractFail, "CONTRACT: FAIL TRIGGER/MARKER", Color.RED);' "static contract fail label"
Assert-Contains $text 'AddLabel(!markerContractFail, "CONTRACT: OK", Color.GRAY);' "static contract ok label"
Assert-Contains $text 'AddLabel(longSetupPulseReady, "RAW SETUP: L", Color.MAGENTA);' "static raw setup long label"
Assert-Contains $text 'AddLabel(shortSetupPulseReady, "RAW SETUP: S", Color.CYAN);' "static raw setup short label"
Assert-Contains $text 'AddLabel(!longSetupPulseReady and !shortSetupPulseReady, "RAW SETUP: -", Color.GRAY);' "static raw setup none label"
Assert-Contains $text 'AddLabel(longContinuationPressure, "RAW CONT: L", Color.MAGENTA);' "static raw continuation long label"
Assert-Contains $text 'AddLabel(shortContinuationPressure, "RAW CONT: S", Color.CYAN);' "static raw continuation short label"
Assert-Contains $text 'AddLabel(!longContinuationPressure and !shortContinuationPressure, "RAW CONT: -", Color.GRAY);' "static raw continuation none label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG SET L200: " + AsText(setupLongRecentCount), Color.MAGENTA);' "recent long setup debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG SET S200: " + AsText(setupShortRecentCount), Color.CYAN);' "recent short setup debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG REV L200: " + AsText(reviewLongRecentCount), Color.MAGENTA);' "recent long review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG REV S200: " + AsText(reviewShortRecentCount), Color.CYAN);' "recent short review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG VIS L/S: " + AsText(visibleLongRecentCount) + "/" + AsText(visibleShortRecentCount), Color.GRAY);' "visible throttled review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG CHOP L/S: " + AsText(reviewChopBlockedLongRecentCount) + "/" + AsText(reviewChopBlockedShortRecentCount), Color.GRAY);' "chop-blocked review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG CONT L/S: " + AsText(reviewContinuationBlockedLongRecentCount) + "/" + AsText(reviewContinuationBlockedShortRecentCount), Color.GRAY);' "continuation-pullback blocked review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG FAST L/S: " + AsText(reviewFastBreakBlockedLongRecentCount) + "/" + AsText(reviewFastBreakBlockedShortRecentCount), Color.GRAY);' "raw fast-break blocked review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG STRUCT L/S: " + AsText(reviewTrendBlockedLongRecentCount) + "/" + AsText(reviewTrendBlockedShortRecentCount), Color.GRAY);' "efficient-score no-structure blocked review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG BOTH L/S: " + AsText(reviewBothSidesLongRecentCount) + "/" + AsText(reviewBothSidesShortRecentCount), Color.GRAY);' "mixed-direction detection debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG ESC L/S: " + AsText(reviewConflictEscapedLongRecentCount) + "/" + AsText(reviewConflictEscapedShortRecentCount), Color.GRAY);' "mixed-direction escape debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG MIX L/S: " + AsText(reviewConflictBlockedLongRecentCount) + "/" + AsText(reviewConflictBlockedShortRecentCount), Color.GRAY);' "mixed-direction blocked review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG FLIP L/S: " + AsText(reviewPressureConflictBlockedLongRecentCount) + "/" + AsText(reviewPressureConflictBlockedShortRecentCount), Color.GRAY);' "raw-pressure flip blocked review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG ANY L/S: " + AsText(reviewLongAnyLoaded) + "/" + AsText(reviewShortAnyLoaded), Color.GRAY);' "any-loaded review debug label"
Assert-Contains $text 'AddLabel(showDebugLabel, "DBG PROBE L/S: " + AsText(scoreProbeLongRecentCount) + "/" + AsText(scoreProbeShortRecentCount), Color.GRAY);' "score-probe debug label"
Assert-True -Condition (-not $text.Contains('AddLabel(yes, "MARKER: " +')) -Message "Complex MARKER label string concatenation can trip TOS parser"
Assert-True -Condition (-not $text.Contains('AddLabel(yes, "CONTRACT: " +')) -Message "Complex CONTRACT label string concatenation can trip TOS parser"
Assert-True -Condition (-not $text.Contains('AddLabel(yes, "RAW: SETUP " +')) -Message "Complex RAW label string concatenation can trip TOS parser"
Assert-True -Condition (-not $text.Contains('AddLabel(dashOK, "MARKER: "')) -Message "Marker state label still depends on showDashboard"
Assert-Contains $text "plot BuildProofDotV0513 =" "hardwired last-bar proof dot"
Assert-Contains $text "if lastVisibleBar then high + liveArrowOff else Double.NaN;" "proof dot is independent of signal"
Assert-Contains $text "BuildProofDotV0513.SetPaintingStrategy(PaintingStrategy.POINTS);" "proof dot uses point rendering"
Assert-Contains $text "def compactMarkerOff = off * 1.4;" "compact marker offset is close to candle to avoid TOS clipping"
Assert-Contains $text "if arrowMarkerLong then low - compactMarkerOff else Double.NaN;" "long marker dot uses close compact offset"
Assert-Contains $text "if arrowMarkerShort then high + compactMarkerOff else Double.NaN;" "short marker dot uses close compact offset"
Assert-Contains $text "low - compactMarkerOff," "long compact marker bubble uses close compact offset"
Assert-Contains $text "high + compactMarkerOff," "short compact marker bubble uses close compact offset"
Assert-Contains $text '"RAW L "' "direct long raw setup bubble label"
Assert-Contains $text '"RAW S "' "direct short raw setup bubble label"
Assert-Contains $text "showRawProofBubbles and rawSetupBubbleLong," "direct long raw setup proof bubble is gated by default-off input"
Assert-Contains $text "showRawProofBubbles and rawSetupBubbleShort," "direct short raw setup proof bubble is gated by default-off input"
Assert-NoRegex $text "(?m)^\s*rawSetupBubble(Long|Short),\s*$" "Raw proof bubbles should not render unconditionally after v0.5.20"
Assert-Contains $text "low - bigArrowOff * 0.75," "long raw setup bubble uses proven larger offset"
Assert-Contains $text "high + bigArrowOff * 0.75," "short raw setup bubble uses proven larger offset"
Assert-Contains $text '"v0.5.42 TEST"' "last-bar build bubble proves chart-bubble path"
Assert-True -Condition (-not $text.Contains('"SPAM L"')) -Message "Hardwired long spam diagnostic bubble is still present"
Assert-True -Condition (-not $text.Contains('"SPAM S"')) -Message "Hardwired short spam diagnostic bubble is still present"
Assert-Contains $text '"FLIP SHORT"' "fast flip short dashboard trigger"
Assert-Contains $text '"FLIP LONG"' "fast flip long dashboard trigger"
Assert-Contains $text '"CONT SHORT"' "continuation short dashboard trigger"
Assert-Contains $text '"CONT LONG"' "continuation long dashboard trigger"
Assert-Contains $text 'else if dashboardContLong then "CONT LONG"' "CONT LONG trigger uses contract boolean"
Assert-Contains $text 'else if dashboardContShort then "CONT SHORT"' "CONT SHORT trigger uses contract boolean"
Assert-True -Condition (-not $text.Contains('else if continuationAnchorShortArrow then "CONT SHORT"')) -Message "CONT SHORT label bypasses dashboardContShort contract"
Assert-True -Condition (-not $text.Contains('else if shortContinuationArrow then "CONT SHORT"')) -Message "CONT SHORT label bypasses dashboardContShort contract"
Assert-True -Condition (-not $text.Contains('"SETUP SHORT"')) -Message "Raw setup should not be a dashboard trigger in quiet-arrow build"
Assert-True -Condition (-not $text.Contains('"SETUP LONG"')) -Message "Raw setup should not be a dashboard trigger in quiet-arrow build"
Assert-Contains $text '"REVIEW SHORT"' "balanced setup-review short dashboard trigger"
Assert-Contains $text '"REVIEW LONG"' "balanced setup-review long dashboard trigger"
Assert-Contains $text '"BREAKDOWN"' "fast breakdown next-state diagnostic"
Assert-Contains $text '"BREAKOUT"' "fast breakout next-state diagnostic"
Assert-Contains $text '"CONTINUE S"' "short continuation next-state diagnostic"
Assert-Contains $text '"CONTINUE L"' "long continuation next-state diagnostic"
Assert-Contains $text '"SETUP READY"' "setup-ready next-state diagnostic"
Assert-Contains $text "def longEntryConfirm = longCandleConfirm or longBreakConfirm or fastBreakoutConfirm;" "fast breakout participates in long entry confirmation"
Assert-Contains $text "def shortEntryConfirm = shortCandleConfirm or shortBreakConfirm or fastBreakdownConfirm;" "fast breakdown participates in short entry confirmation"
Assert-Contains $text "fastBreakdownConfirm" "fast breakdown missed-dump guard"
Assert-Contains $text "def longScoreCrossTrigger" "long score-cross entry trigger"
Assert-Contains $text "def sustainedLongTrigger" "sustained 5/6 long trigger"
Assert-Contains $text "def sustainedShortTrigger" "sustained 5/6 short trigger"
Assert-Contains $text "def cooldownJustCleared" "cooldown clear pulse"
Assert-Contains $text "def longEntryPulse" "anti-starvation long entry pulse"
Assert-Contains $text "def longReadyEntry" "ready long entry fallback"
Assert-Contains $text "def shortReadyEntry" "ready short entry fallback"
Assert-Contains $text "def shortEntryPulse" "anti-starvation short entry pulse"
Assert-Contains $text "def barsSincePlottedEntry" "cooldown driven by plotted entries"
Assert-Contains $text "def entryState" "compile-safe recursive entry state"
Assert-Contains $text "def longEntryCandidate = rawLongEntry or longReadyEntry;" "long entry candidate before entry state"
Assert-Contains $text "def shortEntryCandidate = rawShortEntry or shortReadyEntry;" "short entry candidate before entry state"
Assert-Contains $text "def sameSideLongExpired" "same-side long time reset"
Assert-Contains $text "def sameSideShortExpired" "same-side short time reset"
Assert-Before $text "def entryState" "def newLongEntry" "entryState must be defined before derived long arrow"
Assert-Before $text "def entryState" "def newShortEntry" "entryState must be defined before derived short arrow"
Assert-True -Condition (-not $text.Contains("newLongEntry[1]")) -Message "newLongEntry previous-bar reference reintroduced; use entryState instead"
Assert-True -Condition (-not $text.Contains("newShortEntry[1]")) -Message "newShortEntry previous-bar reference reintroduced; use entryState instead"
Assert-Before $text "def lastEntryDir" "lastEntryDir[1]" "lastEntryDir must be defined before previous-bar use"
Assert-Contains $text "entryState[1] > activeResetSameSideAfterBars" "long same-side reset uses active profile"
Assert-Contains $text "entryState[1] < -activeResetSameSideAfterBars" "short same-side reset uses active profile"
Assert-Contains $text "def practicalLongSetup" "practical long setup arrow layer"
Assert-Contains $text "def practicalShortSetup" "practical short setup arrow layer"
Assert-Contains $text "def practicalLongArrow" "practical long arrow edge"
Assert-Contains $text "def practicalShortArrow" "practical short arrow edge"
Assert-Contains $text "def realLongEntry = newLongEntry or practicalLongArrow or fastFlipLongArrow or longContinuationArrow;" "real long entry includes practical setup edge, fast flip edge, and continuation edge"
Assert-Contains $text "def realShortEntry = newShortEntry or practicalShortArrow or fastFlipShortArrow or shortContinuationArrow;" "real short entry includes practical setup edge, fast flip edge, and continuation edge"
Assert-True -Condition (-not $text.Contains("def realLongEntry = newLongEntry or practicalLongArrow or fastFlipLongArrow or longContinuationArrow or setupPulseLongArrow;")) -Message "Visual-only long setup pulse still resets trade tracking"
Assert-True -Condition (-not $text.Contains("def realShortEntry = newShortEntry or practicalShortArrow or fastFlipShortArrow or shortContinuationArrow or setupPulseShortArrow;")) -Message "Visual-only short setup pulse still resets trade tracking"
Assert-Contains $text "longEntryEdge or longReadyEdge or cooldownJustCleared or longTradeJustUnblocked or sameSideLongExpired" "same-side long waits for next valid candidate after reset"
Assert-Contains $text "shortEntryEdge or shortReadyEdge or cooldownJustCleared or shortTradeJustUnblocked or sameSideShortExpired" "same-side short waits for next valid candidate after reset"
Assert-True -Condition (-not $text.Contains("def anyEntryEdge = longEntryEdge or shortEntryEdge or longReadyEdge or shortReadyEdge;")) -Message "Candidate ready edges still reset cooldown and can starve historical arrows"
Assert-True -Condition (-not $text.Contains("if anyEntryEdge then 0 else barsSinceEntryEdge[1] + 1")) -Message "Cooldown is still driven by candidate entry edges instead of plotted entries"
Assert-Contains $text "def longCautionSetup" "4/6 long caution setup"
Assert-Contains $text "def shortCautionSetup" "4/6 short caution setup"
Assert-Contains $text "def longSignalCaution" "long signal caution label state"
Assert-Contains $text "def shortSignalCaution" "short signal caution label state"
Assert-Contains $text "input showDebugLabel = yes;" "debug label input"
Assert-Contains $text "input debugForceArrows = no;" "temporary forced arrow debug input defaults off"
Assert-Contains $text "input debugPaintBigArrow = no;" "big arrow debug input defaults off"
Assert-Contains $text "def lastVisibleBar = BarNumber() == HighestAll" "last visible bar detector"
Assert-Contains $text "plot DebugBigArrow" "known-visible big debug arrow plot"
Assert-Contains $text "plot DebugBigArrow =" "known-visible short arrow plot declaration"
Assert-True -Condition (-not $text.Contains("if useKnownVisibleSignalArrows and visibleShortSignal then high + liveArrowOff")) -Message "Legacy DebugBigArrow should not duplicate quiet review short arrows"
Assert-Contains $text "if (debugPaintBigArrow and lastVisibleBar) or (debugForceArrows and debugForcedShortArrow) then high + bigArrowOff" "debug short arrows keep big diagnostic offset"
Assert-Contains $text "DebugBigArrow.SetPaintingStrategy(PaintingStrategy.ARROW_DOWN);" "big debug arrow painting strategy"
Assert-Contains $text "DebugBigArrow.SetLineWeight(5);" "big debug arrow line weight"
Assert-Contains $text "DebugBigArrow.SetDefaultColor(Color.CYAN);" "big debug arrow color"
Assert-Contains $text "plot DebugBigUpArrow =" "known-visible long arrow plot declaration"
Assert-True -Condition (-not $text.Contains("if useKnownVisibleSignalArrows and visibleLongSignal then low - liveArrowOff")) -Message "Legacy DebugBigUpArrow should not duplicate quiet review long arrows"
Assert-Contains $text "if debugForceArrows and debugForcedLongArrow then low - bigArrowOff" "debug long arrows keep big diagnostic offset"
Assert-Contains $text "DebugBigUpArrow.SetPaintingStrategy(PaintingStrategy.ARROW_UP);" "big up debug arrow painting strategy"
Assert-Contains $text "DebugBigUpArrow.SetLineWeight(5);" "big up debug arrow line weight"
Assert-Contains $text "DebugBigUpArrow.SetDefaultColor(Color.MAGENTA);" "big up debug arrow color"
Assert-Contains $text '"BIG TEST ARROW"' "big debug arrow bubble"
Assert-Contains $text '"BIG TEST"' "big debug trigger dashboard state"
Assert-Contains $text "def debugForcedLongArrow = debugForceArrows and longScore >= triggerThreshold and longScore > shortScore;" "forced long arrow condition ignores trade/RVOL"
Assert-Contains $text "def debugForcedShortArrow = debugForceArrows and shortScore >= triggerThreshold and shortScore > longScore;" "forced short arrow condition ignores trade/RVOL"
Assert-True -Condition (-not $text.Contains("def debugForcedLongArrow = debugForceArrows and longScore >= triggerThreshold and longScore > shortScore and longTradeOK;")) -Message "Debug forced long arrow is still blocked by trade/RVOL"
Assert-True -Condition (-not $text.Contains("def debugForcedShortArrow = debugForceArrows and shortScore >= triggerThreshold and shortScore > longScore and shortTradeOK;")) -Message "Debug forced short arrow is still blocked by trade/RVOL"
Assert-Contains $text "def arrowOff = Max(off, atr * 0.12);" "ATR-aware arrow visibility offset"
Assert-Contains $text "def signalArrowOff = Max(off * 8, atr * 0.30);" "larger visible real-entry arrow offset"
Assert-Contains $text "def liveArrowOff = Max(off * 18, atr * 0.50);" "closer known-visible live arrow offset"
Assert-Contains $text "def reviewArrowOff = Max(liveArrowOff, atr * (reviewStopATRFactor + reviewArrowRiskBufferATR));" "review arrows are offset beyond the review stop bubble"
Assert-True -Condition (-not $text.Contains("if useKnownVisibleSignalArrows and realShortEntry then high + liveArrowOff")) -Message "Known-visible short plot still ignores continuation anchors"
Assert-True -Condition (-not $text.Contains("if useKnownVisibleSignalArrows and realLongEntry then low - liveArrowOff")) -Message "Known-visible long plot still ignores continuation anchors"
Assert-True -Condition (-not $text.Contains("plot SignalLongV055Arrow = if realLongEntry")) -Message "Real long entries still use the v0.5.5 hidden-prone plot"
Assert-True -Condition (-not $text.Contains("plot SignalShortV055Arrow = if realShortEntry")) -Message "Real short entries still use the v0.5.5 hidden-prone plot"
Assert-True -Condition (-not $text.Contains("plot VisibleLongArrow = if newLongEntry or debugForcedLongArrow")) -Message "Real long arrow still includes forced debug arrows"
Assert-True -Condition (-not $text.Contains("plot VisibleShortArrow = if newShortEntry or debugForcedShortArrow")) -Message "Real short arrow still includes forced debug arrows"
Assert-Contains $text "showFailsafeSignalBubbles and setupPulseLongArrow" "ungated failsafe long setup bubble"
Assert-Contains $text "showFailsafeSignalBubbles and setupPulseShortArrow" "ungated failsafe short setup bubble"
Assert-Contains $text '"FORCED: "' "forced arrow condition dashboard label"
Assert-Contains $text "Color.MAGENTA" "forced long debug arrow color"
Assert-Contains $text "Color.CYAN" "forced short debug arrow color"
Assert-Contains $text '"TEST L "' "forced long debug bubble"
Assert-Contains $text '"TEST S "' "forced short debug bubble"
Assert-Contains $text "debugForceArrows and debugForcedLongArrow and !realLongEntry," "forced long debug bubble ignores signal-bubble toggle"
Assert-Contains $text "debugForceArrows and debugForcedShortArrow and !realShortEntry," "forced short debug bubble ignores signal-bubble toggle"
Assert-True -Condition (-not $text.Contains("showSignalBubbles and debugForcedLongArrow")) -Message "Forced long debug bubble is still hidden by showSignalBubbles"
Assert-True -Condition (-not $text.Contains("showSignalBubbles and debugForcedShortArrow")) -Message "Forced short debug bubble is still hidden by showSignalBubbles"
Assert-Contains $text '"TEST LONG"' "forced long trigger dashboard state"
Assert-Contains $text '"TEST SHORT"' "forced short trigger dashboard state"
Assert-Contains $text '"DEBUG FORCE ARROWS"' "visible forced-arrow debug dashboard label"
Assert-Contains $text '"BLOCKED BY: "' "hard-block diagnostic dashboard label"
Assert-Contains $text '"CAUTION BY: "' "caution diagnostic dashboard label"
Assert-Contains $text '"NEXT: "' "next-trigger diagnostic dashboard label"
Assert-True -Condition (-not $text.Contains('"WHY: "')) -Message "Old combined WHY diagnostic label can confuse caution with hard block"
Assert-Contains $text '"SCORE"' "score-first diagnostic state"
Assert-Contains $text '"TIE"' "tie diagnostic state"
Assert-Contains $text '"SETUP: " +' "setup dashboard label"
Assert-True -Condition (-not $text.Contains('"SETUP: " + AsText(dashScore)')) -Message "SETUP label still uses decimal AsText(dashScore)"
Assert-Contains $text "longScore < triggerThreshold" "same-side long reset below trigger"
Assert-Contains $text "shortScore < triggerThreshold" "same-side short reset below trigger"
Assert-Contains $text "def shortCandleConfirm" "short candle confirmation"
Assert-Contains $text "def shortScoreCrossTrigger" "short score-cross entry trigger"
Assert-Contains $text "input minRelVolume = 0.80;" "5m caution RVOL threshold"
Assert-Contains $text "input blockRelVolume = 0.00;" "RVOL no longer hard-blocks qualified setups by default"
Assert-Contains $text "input lowVolumeMomentumATRFactor = 1.20;" "low-volume impulse override range factor"
Assert-True -Condition (-not $text.Contains("input blockRelVolume = 0.10;")) -Message "Old 0.10 RVOL hard block is still present"
Assert-True -Condition (-not $text.Contains("input blockRelVolume = 0.35;")) -Message "Old 0.35 RVOL hard block is still present"
Assert-True -Condition (-not $text.Contains("input blockRelVolume = 0.60;")) -Message "Old 0.60 RVOL hard block is still present"
Assert-Contains $text "def extremeLowRelVolume" "extreme low relative volume gate"
Assert-Contains $text "def exceptionalLongMomentum" "exceptional long momentum override"
Assert-Contains $text "def exceptionalShortMomentum" "exceptional short momentum override"
Assert-Contains $text "def lowVolumeLongMomentum" "low-volume long momentum override"
Assert-Contains $text "def lowVolumeShortMomentum" "low-volume short momentum override"
Assert-Contains $text "def longVolumeOK" "long direction volume gate"
Assert-Contains $text "def shortVolumeOK" "short direction volume gate"
Assert-Contains $text "def longVolumeOK = yes;" "long RVOL is not a hard entry blocker"
Assert-Contains $text "def shortVolumeOK = yes;" "short RVOL is not a hard entry blocker"
Assert-Contains $text "def tradeBlocked = structureBlocked;" "trade blocked state does not hard-block solely on RVOL"
Assert-True -Condition (-not $text.Contains("def longVolumeOK = !extremeLowRelVolume")) -Message "Long volume gate still hard-blocks extreme RVOL"
Assert-True -Condition (-not $text.Contains("def shortVolumeOK = !extremeLowRelVolume")) -Message "Short volume gate still hard-blocks extreme RVOL"
Assert-Contains $text "def fastBreakVolumeOK = relVol >= minRelVolume or candleTR >= avgTR20 * lowVolumeMomentumATRFactor;" "fast break can confirm on low-volume impulse"
Assert-Contains $text "def tradeBlocked" "trade blocked state"
Assert-Contains $text "def longTradeOK" "long trade permission state"
Assert-Contains $text "def shortTradeOK" "short trade permission state"
Assert-Contains $text "def trendResetLong" "long trend reset state"
Assert-Contains $text "def trendResetShort" "short trend reset state"
Assert-Contains $text "def continuationLongSignal" "long continuation signal"
Assert-Contains $text "def continuationShortSignal" "short continuation signal"
Assert-Contains $text "def activeTradeScore" "active trade score"
Assert-Contains $text "def peakTradeScore" "peak trade score"
Assert-Contains $text "def longDanger" "long danger state"
Assert-Contains $text "def shortDanger" "short danger state"
Assert-Contains $text "def longDangerEdge" "long danger edge"
Assert-Contains $text "def shortDangerEdge" "short danger edge"
Assert-Contains $text "def longProfitMove = close - activeEntryPrice;" "directional long profit calculation"
Assert-Contains $text "def shortProfitMove = activeEntryPrice - close;" "directional short profit calculation"
Assert-Contains $text "if realLongEntry or realShortEntry then close else activeEntryPrice[1]" "active entry price uses practical real entries"
Assert-Contains $text "if realLongEntry or realShortEntry then atr else lockedATR[1]" "locked ATR uses practical real entries"
Assert-Contains $text "if realLongEntry then 1" "active long direction uses practical real entry"
Assert-Contains $text "else if realShortEntry then -1" "active short direction uses practical real entry"
Assert-Contains $text "def longTargetPrice = activeEntryPrice + lockedATR * targetATRFactor;" "long ATR target"
Assert-Contains $text "def shortTargetPrice = activeEntryPrice - lockedATR * targetATRFactor;" "short ATR target"
Assert-Contains $text "def longStopPrice = activeEntryPrice - lockedATR * stopATRFactor;" "long ATR stop"
Assert-Contains $text "def shortStopPrice = activeEntryPrice + lockedATR * stopATRFactor;" "short ATR stop"
Assert-Contains $text "def reviewTargetStopDir =" "review-only target/stop direction state"
Assert-Contains $text "if visibleLongSignal then 1" "review target/stop starts on visible long arrows only"
Assert-Contains $text "else if visibleShortSignal then -1" "review target/stop starts on visible short arrows only"
Assert-Contains $text "def reviewTargetStopEntry =" "review-only target/stop entry price state"
Assert-Contains $text "if visibleLongSignal or visibleShortSignal then close else reviewTargetStopEntry[1]" "review target/stop entry uses visible review arrows"
Assert-Contains $text "def reviewTargetStopATR =" "review-only target/stop ATR state"
Assert-Contains $text "if visibleLongSignal or visibleShortSignal then atr else reviewTargetStopATR[1]" "review target/stop ATR locks at visible review arrow"
Assert-Contains $text "def reviewTargetStopActive = reviewTargetStopDir != 0 and reviewTargetStopAge <= Max(1, reviewTargetStopHoldBars);" "review target/stop plan expires by hold window"
Assert-Contains $text "def reviewTargetPrice = if reviewTargetStopDir == 1 then reviewTargetStopEntry + reviewTargetStopATR * reviewTargetATRFactor else if reviewTargetStopDir == -1 then reviewTargetStopEntry - reviewTargetStopATR * reviewTargetATRFactor else Double.NaN;" "review target uses wider review-only ATR math without real trade state"
Assert-Contains $text "def reviewStopPrice = if reviewTargetStopDir == 1 then reviewTargetStopEntry - reviewTargetStopATR * reviewStopATRFactor else if reviewTargetStopDir == -1 then reviewTargetStopEntry + reviewTargetStopATR * reviewStopATRFactor else Double.NaN;" "review stop uses review-only ATR math without real trade state"
Assert-Contains $text 'AddChartBubble(showReviewTargetStopBubbles and visibleLongSignal, close + atr * reviewTargetATRFactor, "R-TP", GlobalColor("CautionAmber"), yes);' "review long target bubble uses review-only ATR factor"
Assert-Contains $text 'AddChartBubble(showReviewTargetStopBubbles and visibleLongSignal, close - atr * reviewStopATRFactor, "R-SL", Color.RED, no);' "review long stop bubble uses review-only ATR factor"
Assert-Contains $text 'AddChartBubble(showReviewTargetStopBubbles and visibleShortSignal, close - atr * reviewTargetATRFactor, "R-TP", GlobalColor("CautionAmber"), no);' "review short target bubble uses review-only ATR factor"
Assert-Contains $text 'AddChartBubble(showReviewTargetStopBubbles and visibleShortSignal, close + atr * reviewStopATRFactor, "R-SL", Color.RED, yes);' "review short stop bubble uses review-only ATR factor"
Assert-Contains $text "plot ReviewTargetLineV0542 =" "review-only target line plot"
Assert-Contains $text "plot ReviewStopLineV0542 =" "review-only stop line plot"
Assert-Contains $text "if showReviewTargetStopLines and reviewTargetStopActive then reviewTargetPrice else Double.NaN;" "review target line is controlled by review-only toggle"
Assert-Contains $text "if showReviewTargetStopLines and reviewTargetStopActive then reviewStopPrice else Double.NaN;" "review stop line is controlled by review-only toggle"
Assert-Contains $text "if showTargetStopLines and activeDir == 1 then longTargetPrice" "long target only while trade is active"
Assert-Contains $text "if showTargetStopLines and activeDir == -1 then shortTargetPrice" "short target only while trade is active"
Assert-Contains $text "if showTargetStopLines and targetHit and activeDir[1] == 1 then longTargetPrice[1]" "long target visible on hit bar"
Assert-Contains $text "if showTargetStopLines and stopHit and activeDir[1] == 1 then longStopPrice[1]" "long stop visible on hit bar"
Assert-Contains $text "showSignalBubbles and realLongEntry" "compact long signal bubble"
Assert-Contains $text "showSignalBubbles and realShortEntry" "compact short signal bubble"
Assert-Contains $text "AddChartBubble(showContinuationBubbles and continuationLongSignal" "long continuation bubble"
Assert-Contains $text "AddChartBubble(showContinuationBubbles and continuationShortSignal" "short continuation bubble"
Assert-Contains $text "AddChartBubble(showDangerBubbles and longDangerEdge" "long danger bubble"
Assert-Contains $text "AddChartBubble(showDangerBubbles and shortDangerEdge" "short danger bubble"
Assert-Contains $text '"ENTRY L "' "entry long bubble label"
Assert-Contains $text '"ADD L "' "add long bubble label"
Assert-Contains $text '"DANGER L "' "danger long bubble label"
Assert-Contains $text '"PT"' "profit target bubble label"
Assert-Contains $text '"SL"' "stop loss bubble label"
Assert-Contains $text '"R-TP"' "review target bubble label"
Assert-Contains $text '"R-SL"' "review stop bubble label"
Assert-NoRegex $text "(?m)^\s*def\s+(?:activeEntryPrice|lockedATR|activeDir|longTargetPrice|shortTargetPrice|longStopPrice|shortStopPrice)\s*=.*reviewTargetStop" "Review target/stop diagnostics must not feed real PT/SL tracking state"
Assert-NoRegex $text "(?s)Alert\s*\((?:(?!\);).)*reviewTargetStop" "Review target/stop diagnostics must not feed alerts"
Assert-Contains $text '"TRADE: "' "trade dashboard label"
Assert-Contains $text '"OK"' "trade ok dashboard state"
Assert-Contains $text '"CAUTION"' "risk caution dashboard state"
Assert-Contains $text '"BLOCKED"' "trade blocked dashboard state"
Assert-True -Condition (-not $text.Contains("Color.YELLOW")) -Message "Bright Color.YELLOW is still present and hard to read with white TOS text"
Assert-Contains $text 'GlobalColor("CautionAmber")' "amber caution dashboard/bubble colors"

Assert-True -Condition (-not $text.Contains("AbsValue(close - entryPrice)")) -Message "Old absolute target math is still present"
Assert-True -Condition (-not $text.Contains('"RISK: "')) -Message "Old RISK dashboard label is still present"
Assert-True -Condition (-not $text.Contains('"NORMAL"')) -Message "Old risk NORMAL dashboard state is still present"
Assert-True -Condition (-not $text.Contains("plot NeutralUpArrow")) -Message "Old neutral up arrow plot is still present"
Assert-True -Condition (-not $text.Contains("plot NeutralDownArrow")) -Message "Old neutral down arrow plot is still present"
Assert-True -Condition (-not $text.Contains("plot ConfluenceUpArrow")) -Message "Old confluence up arrow plot is still present"
Assert-True -Condition (-not $text.Contains("plot ConfluenceDownArrow")) -Message "Old confluence down arrow plot is still present"

Write-Host "Simplified indicator verification passed."
